"""Emit app/supabase/migrations/20260827000001_popia_2026_pack.sql from the golden zip."""
from __future__ import annotations

from pathlib import Path

from popia_2026_pack import (
    LEGEND_BEGIN,
    LEGEND_END,
    PACK_ROWS_BEGIN,
    PACK_ROWS_END,
    legend_sql,
    pack_rows_sql,
    parse_pack,
)

OUT = (
    Path(__file__).resolve().parents[1]
    / "supabase"
    / "migrations"
    / "20260827000001_popia_2026_pack.sql"
)

PREFIX = r"""-- POPIA 2026 Stage 1 pack (ISO 27701-aligned auditor sheets) + SME/large branch.
-- Source: docs/assessment-sheets/assessment_popi_2026_1.zip
-- Rows between the PACK/LEGEND markers are generated by app/tests/generate_popia_2026_migration.py
-- from that zip; app/tests/test_popia_2026_pack_parity.py asserts they match.

BEGIN;

ALTER TABLE public.client_orgs
  ADD COLUMN IF NOT EXISTS org_scale text CHECK (org_scale IS NULL OR org_scale IN ('sme', 'large'));
COMMENT ON COLUMN public.client_orgs.org_scale IS
  'Advisor-deemed organisation scale. SME edition in the 2026 POPIA pack is ≤10 users.';

ALTER TABLE public.assessment_sessions
  ADD COLUMN IF NOT EXISTS org_scale text CHECK (org_scale IS NULL OR org_scale IN ('sme', 'large'));
COMMENT ON COLUMN public.assessment_sessions.org_scale IS
  'Snapshot of client org_scale at assessment create. Scoring and question load use this, not the live client value.';

ALTER TABLE public.assessment_questions
  ADD COLUMN IF NOT EXISTS applies_to text NOT NULL DEFAULT 'all'
    CHECK (applies_to IN ('all', 'sme', 'large'));
COMMENT ON COLUMN public.assessment_questions.applies_to IS
  'all = every org; large = large-only (the 17 S4 extras). SME branch is applies_to=all.';

ALTER TABLE public.content_packs
  ADD COLUMN IF NOT EXISTS metadata jsonb;

UPDATE public.assessment_questions
   SET active = FALSE
 WHERE framework = 'popia' AND active = TRUE;

INSERT INTO public.content_packs (practice_id, framework_key, version, label, status, metadata)
VALUES (NULL, 'popia', 2, 'POPIA ISO27701 audit 2026', 'published',
"""

MID = r"""
);

INSERT INTO public.assessment_questions
  (framework, content_pack_id, section_id, section_name, subsection, question_number,
   question, why_matters, regulatory_ref, risk, evidence_req, remediation, applies_to, uid)
SELECT 'popia', cp.id, x.section_id, x.section_name, x.subsection, x.qn,
       x.question, x.why, x.ref, x.risk, x.evidence, x.remediation, x.applies_to, x.uid
FROM (SELECT id FROM public.content_packs
      WHERE framework_key = 'popia' AND version = 2 AND practice_id IS NULL) cp,
(VALUES
"""

SUFFIX = r"""
) AS x(section_id, section_name, subsection, qn, question, why, ref, risk, evidence, remediation, applies_to, uid);

-- ---------- create_client_org: capture deemed scale ----------
DROP FUNCTION IF EXISTS public.create_client_org(text, text, text, text, text);
CREATE FUNCTION public.create_client_org(
    p_name text, p_registration_no text DEFAULT NULL, p_industry text DEFAULT NULL,
    p_contact_name text DEFAULT NULL, p_contact_email text DEFAULT NULL,
    p_org_scale text DEFAULT 'large')
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE pid uuid; cid uuid;
BEGIN
  SELECT practice_id INTO pid FROM memberships
    WHERE user_id = auth.uid() AND role = 'practice_owner';
  IF pid IS NULL THEN RAISE EXCEPTION 'only practice owners may create client instances'; END IF;
  IF p_org_scale IS NOT NULL AND p_org_scale NOT IN ('sme', 'large') THEN
    RAISE EXCEPTION 'org_scale must be sme or large';
  END IF;
  INSERT INTO client_orgs (practice_id, name, registration_no, industry, contact_name, contact_email, org_scale)
    VALUES (pid, p_name, p_registration_no, p_industry, p_contact_name, p_contact_email, COALESCE(p_org_scale, 'large'))
    RETURNING id INTO cid;
  INSERT INTO tracks (client_org_id, track_kind)
    VALUES (cid, 'privacy'), (cid, 'cyber');
  INSERT INTO billing_events (practice_id, client_org_id, event_type, detail)
    VALUES (pid, cid, 'instance.created', jsonb_build_object('name', p_name, 'by', auth.uid()));
  INSERT INTO notifications (practice_id, kind, message)
    VALUES (pid, 'billing',
            format('Client instance "%s" created — this instance is billable.', p_name));
  INSERT INTO audit_log (user_id, practice_id, action, detail)
    VALUES (auth.uid(), pid, 'client_org.created', jsonb_build_object('client_org', cid, 'name', p_name, 'org_scale', COALESCE(p_org_scale, 'large')));
  RETURN cid;
END $$;
REVOKE EXECUTE ON FUNCTION public.create_client_org(text, text, text, text, text, text) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.create_client_org(text, text, text, text, text, text) TO authenticated;

-- ---------- create_assessment: snapshot org_scale ----------
DROP FUNCTION IF EXISTS public.create_assessment(uuid, text, text, text, text, date, text);
CREATE FUNCTION public.create_assessment(
    p_client_org_id UUID, p_framework TEXT, p_title TEXT, p_org_name TEXT,
    p_auditor_name TEXT, p_audit_date DATE, p_audit_ref TEXT,
    p_org_scale TEXT DEFAULT NULL)
RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE aid uuid; v_kind text; v_track uuid; v_stage int; v_scale text;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'not authenticated'; END IF;
  IF p_client_org_id NOT IN (SELECT public.allowed_client_orgs()) THEN
    RAISE EXCEPTION 'Access denied to client organisation';
  END IF;
  IF public.current_role_name() = 'read_only' THEN
    RAISE EXCEPTION 'read_only users cannot create assessments';
  END IF;

  SELECT track_kind INTO v_kind FROM frameworks WHERE key = p_framework;
  IF v_kind IS NULL THEN RAISE EXCEPTION 'unknown framework %', p_framework; END IF;
  SELECT id, current_stage INTO v_track, v_stage
    FROM tracks WHERE client_org_id = p_client_org_id AND track_kind = v_kind;
  IF v_track IS NULL THEN
    v_track := public.create_track(p_client_org_id, v_kind);
    v_stage := 0;
  END IF;

  v_scale := p_org_scale;
  IF v_scale IS NULL THEN
    SELECT org_scale INTO v_scale FROM client_orgs WHERE id = p_client_org_id;
  END IF;
  IF v_scale IS NULL THEN v_scale := 'large'; END IF;
  IF v_scale NOT IN ('sme', 'large') THEN RAISE EXCEPTION 'org_scale must be sme or large'; END IF;

  INSERT INTO public.assessment_sessions
    (client_org_id, framework, title, org_name, auditor_name, audit_date, audit_ref, track_id, org_scale)
  VALUES (p_client_org_id, p_framework, p_title, p_org_name, p_auditor_name, p_audit_date, p_audit_ref, v_track, v_scale)
  RETURNING id INTO aid;

  IF v_stage = 0 THEN
    PERFORM public.advance_track_stage(v_track, 1, 'Stage 1: assessment started');
  END IF;

  INSERT INTO public.audit_log (user_id, practice_id, action, detail)
  VALUES (auth.uid(), public.current_practice(), 'assessment.created',
          jsonb_build_object('assessment_id', aid, 'client_org_id', p_client_org_id, 'org_scale', v_scale));
  RETURN aid;
END $$;
REVOKE EXECUTE ON FUNCTION public.create_assessment(uuid, text, text, text, text, date, text, text) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.create_assessment(uuid, text, text, text, text, date, text, text) TO authenticated;

-- ---------- scoring: POPIA in-scope = sections 1-6 matching snapshotted org_scale ----------
CREATE OR REPLACE FUNCTION public.assessment_question_in_scope(
    p_framework text, p_section_id int, p_applies_to text, p_org_scale text)
RETURNS boolean LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE
    WHEN p_framework IS DISTINCT FROM 'popia' THEN TRUE
    WHEN p_section_id < 1 OR p_section_id > 6 THEN FALSE
    WHEN COALESCE(p_applies_to, 'all') = 'all' THEN TRUE
    WHEN COALESCE(p_org_scale, 'large') = p_applies_to THEN TRUE
    ELSE FALSE
  END
$$;
REVOKE EXECUTE ON FUNCTION public.assessment_question_in_scope(text, int, text, text) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.assessment_question_in_scope(text, int, text, text) TO authenticated;

CREATE OR REPLACE FUNCTION public.calculate_assessment_score(p_session_id UUID)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  result JSONB;
  v_framework TEXT;
  v_org_scale TEXT;
  v_total_questions INTEGER;
  v_answered_non_na INTEGER;
  v_overall_achieved INTEGER;
  v_overall_total INTEGER;
  v_completion_pct INTEGER;
  v_section_scores JSONB;
  v_risk_summary JSONB;
  v_critical_gaps INTEGER;
BEGIN
  SELECT framework, org_scale INTO v_framework, v_org_scale
  FROM public.assessment_sessions
  WHERE id = p_session_id;

  SELECT COUNT(*) INTO v_total_questions
  FROM public.assessment_questions q
  WHERE q.framework = v_framework AND q.active = TRUE
    AND public.assessment_question_in_scope(q.framework, q.section_id, q.applies_to, v_org_scale);

  SELECT COUNT(*) INTO v_answered_non_na
  FROM public.assessment_responses r
  JOIN public.assessment_questions q ON r.question_id = q.id
  WHERE r.session_id = p_session_id
    AND r.response IS NOT NULL AND r.response <> '' AND r.response <> 'na'
    AND public.assessment_question_in_scope(q.framework, q.section_id, q.applies_to, v_org_scale);

  v_completion_pct := CASE
    WHEN v_total_questions > 0
    THEN ROUND(v_answered_non_na::numeric / v_total_questions * 100)
    ELSE 0
  END;

  SELECT
    SUM(CASE WHEN r.response = 'fully_compliant' THEN 2
             WHEN r.response = 'partial' THEN 1
             ELSE 0 END) INTO v_overall_achieved
  FROM public.assessment_responses r
  JOIN public.assessment_questions q ON r.question_id = q.id
  WHERE r.session_id = p_session_id AND r.response <> 'na'
    AND public.assessment_question_in_scope(q.framework, q.section_id, q.applies_to, v_org_scale);

  SELECT COUNT(*) * 2 INTO v_overall_total
  FROM public.assessment_responses r
  JOIN public.assessment_questions q ON r.question_id = q.id
  WHERE r.session_id = p_session_id AND r.response <> 'na'
    AND public.assessment_question_in_scope(q.framework, q.section_id, q.applies_to, v_org_scale);

  SELECT COALESCE(jsonb_object_agg(
    'S' || sec.section_id,
    jsonb_build_object(
      'section_name', sec.section_name,
      'score', sec.achieved_points,
      'total', sec.total_points,
      'pct', CASE WHEN sec.total_points > 0
                  THEN ROUND(sec.achieved_points::numeric / sec.total_points * 100)
                  ELSE 0 END
    )
  ), '{}'::jsonb) INTO v_section_scores
  FROM (
    SELECT
      q.section_id,
      MAX(q.section_name) as section_name,
      SUM(CASE WHEN r.response = 'fully_compliant' THEN 2
               WHEN r.response = 'partial' THEN 1
               ELSE 0 END) as achieved_points,
      COUNT(CASE WHEN r.response <> 'na' THEN 1 END) * 2 as total_points
    FROM public.assessment_responses r
    JOIN public.assessment_questions q ON r.question_id = q.id
    WHERE r.session_id = p_session_id
      AND public.assessment_question_in_scope(q.framework, q.section_id, q.applies_to, v_org_scale)
    GROUP BY q.section_id
  ) sec;

  SELECT COALESCE(jsonb_object_agg(risk_level, cnt), '{}'::jsonb) INTO v_risk_summary
  FROM (
    SELECT q.risk as risk_level, COUNT(*) as cnt
    FROM public.assessment_responses r
    JOIN public.assessment_questions q ON r.question_id = q.id
    WHERE r.session_id = p_session_id AND r.response = 'non_compliant'
      AND public.assessment_question_in_scope(q.framework, q.section_id, q.applies_to, v_org_scale)
    GROUP BY q.risk
  ) rs;

  SELECT COUNT(*) INTO v_critical_gaps
  FROM public.assessment_responses r
  JOIN public.assessment_questions q ON r.question_id = q.id
  WHERE r.session_id = p_session_id AND r.response = 'non_compliant' AND q.risk = 'Critical'
    AND public.assessment_question_in_scope(q.framework, q.section_id, q.applies_to, v_org_scale);

  result := jsonb_build_object(
    'section_scores', v_section_scores,
    'overall', jsonb_build_object(
      'score', COALESCE(v_overall_achieved, 0),
      'total', COALESCE(v_overall_total, 0),
      'pct', CASE WHEN v_overall_total > 0
                  THEN ROUND(v_overall_achieved::numeric / v_overall_total * 100)
                  ELSE 0 END,
      'rating', CASE
        WHEN v_overall_total = 0 THEN 'significant_gaps'
        WHEN v_overall_achieved::numeric / v_overall_total >= 0.75 THEN 'satisfactory'
        WHEN v_overall_achieved::numeric / v_overall_total >= 0.50 THEN 'requires_improvement'
        ELSE 'significant_gaps'
      END
    ),
    'completion_pct', v_completion_pct,
    'risk_summary', v_risk_summary,
    'critical_gaps', v_critical_gaps
  );
  RETURN result;
END;
$$;

GRANT EXECUTE ON FUNCTION public.calculate_assessment_score(uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.calculate_assessment_score(uuid) FROM anon, public;

NOTIFY pgrst, 'reload schema';

COMMIT;
"""


def main() -> None:
    pack = parse_pack()
    legend = legend_sql(pack)
    rows = pack_rows_sql(pack)
    body = (
        PREFIX
        + LEGEND_BEGIN
        + "\n"
        + legend
        + "\n"
        + LEGEND_END
        + MID
        + PACK_ROWS_BEGIN
        + "\n"
        + rows
        + "\n"
        + PACK_ROWS_END
        + SUFFIX
    )
    OUT.write_text(body)
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes, {len(pack['advisor'])} advisor + {len(pack['s1a'])} s1a)")


if __name__ == "__main__":
    main()
