-- POPIA Module 2: Lawful Processing - Eight Conditions (15 questions)
INSERT INTO public.assessment_questions (framework, section_id, section_name, subsection, question_number, question, why_matters, regulatory_ref, risk, evidence_req, remediation, uid) VALUES
-- Condition 1: Accountability (3 questions)
('popia', 2, 'Lawful Processing - Eight Conditions', 'Accountability', 1, 'Has the organisation designated a senior executive with ultimate responsibility for POPIA compliance?', 'Section 5(2) accountability requires that a responsible person is designated for ensuring compliance. This person is accountable for the organisation''s overall compliance posture.', 'POPIA Section 5(2) accountability; ISO 27701 cl.5.1 leadership', 'Critical', 'Board resolution or executive appointment letter; job description for responsible executive; reporting lines; evidence of regular compliance reporting.', 'Designate senior executive (often CEO or COO) via board resolution. Document their responsibilities for POPIA compliance. Establish reporting lines and regular compliance updates.', 'P2_ACC_1'),

('popia', 2, 'Lawful Processing - Eight Conditions', 'Accountability', 2, 'Does the responsible executive have sufficient authority and resources to ensure compliance?', 'Without adequate authority and resources, the responsible executive cannot effectively ensure compliance across the organisation.', 'POPIA Section 5(2) accountability; ISO 27701 cl.5.1 leadership commitment', 'Critical', 'Authority delegation document; budget allocation for compliance; executive sponsorship evidence; organisational chart showing authority.', 'Ensure responsible executive has appropriate authority in organisational hierarchy. Allocate adequate budget for compliance activities. Document authority and resource allocation.', 'P2_ACC_2'),

('popia', 2, 'Lawful Processing - Eight Conditions', 'Accountability', 3, 'Is there documented evidence of the responsible executive''s compliance oversight activities?', 'Section 5(2) accountability requires organisations to demonstrate compliance. Regular oversight activities provide evidence of this commitment.', 'POPIA Section 5(2) accountability; ISO 27701 cl.9.3 management review', 'High', 'Meeting minutes showing compliance discussions; review reports; executive sign-off on compliance documents; audit trail of oversight activities.', 'Schedule regular compliance review meetings with responsible executive. Document meeting minutes and decisions. Obtain executive sign-off on key compliance documents.', 'P2_ACC_3'),

-- Condition 2: Processing Limitation (2 questions)
('popia', 2, 'Lawful Processing - Eight Conditions', 'Processing Limitation', 4, 'Does the organisation collect only the personal information that is necessary for its stated purposes?', 'Section 9(1) processing limitation requires that organisations collect only the personal information needed for the specific processing purpose. Over-collection is prohibited.', 'POPIA Section 9(1) processing limitation; ISO 27701 cl.7.2.1 data minimisation', 'Critical', 'Data inventory showing purpose for each data element; data collection procedures; data minimisation guidelines; evidence of data collection controls.', 'Conduct data inventory to identify all personal information processed. Document specific purpose for each data element. Implement data minimisation guidelines and controls.', 'P2_PL_1'),

('popia', 2, 'Lawful Processing - Eight Conditions', 'Processing Limitation', 5, 'Are there controls in place to prevent over-collection of personal information?', 'Section 9(1) processing limitation requires organisations to implement measures to prevent over-collection beyond what is necessary.', 'POPIA Section 9(1) processing limitation; ISO 27701 cl.7.2.1 data minimisation', 'High', 'Data collection form controls; approval processes for new data collection; regular reviews of data holdings; data deletion procedures.', 'Implement controls on data collection forms and processes. Require approval for new data collection. Conduct regular reviews of data holdings and delete unnecessary data.', 'P2_PL_2'),

-- Condition 3: Purpose Specification (2 questions)
('popia', 2, 'Lawful Processing - Eight Conditions', 'Purpose Specification', 6, 'Is the specific purpose for processing personal information clearly documented and communicated?', 'Section 11(1) purpose specification requires that the purpose for processing be clearly specified at the time of collection and communicated to data subjects.', 'POPIA Section 11(1) purpose specification; ISO 27701 cl.7.2.2 purpose specification', 'Critical', 'Privacy notices; data collection forms; purpose documentation; communication records with data subjects.', 'Document specific purpose for each processing activity. Update privacy notices and data collection forms. Maintain records of purpose communication to data subjects.', 'P2_PS_1'),

('popia', 2, 'Lawful Processing - Eight Conditions', 'Purpose Specification', 7, 'Are changes to processing purpose evaluated for compliance before implementation?', 'Section 11(3) prohibits processing for a new purpose without further processing unless the data subject consents or the change is authorised by law or regulation.', 'POPIA Section 11(3) purpose change; ISO 27701 cl.7.2.2 purpose specification', 'High', 'Purpose change evaluation process; consent records for purpose changes; legal authorisation documentation; impact assessment records.', 'Implement purpose change evaluation process. Obtain consent for new purposes where required. Document legal authorisation and conduct impact assessments.', 'P2_PS_2'),

-- Condition 4: Further Processing Limitation (2 questions)
('popia', 2, 'Lawful Processing - Eight Conditions', 'Further Processing Limitation', 8, 'Does the organisation evaluate further processing activities for compliance before implementation?', 'Section 11(3) requires evaluation of further processing to ensure it aligns with the original purpose or meets legal exceptions.', 'POPIA Section 11(3) further processing; ISO 27701 cl.7.2.2 purpose specification', 'High', 'Further processing evaluation checklist; legal review documentation; impact assessments; approval records for further processing.', 'Implement evaluation process for further processing activities. Conduct legal review and impact assessments. Document approval decisions and rationale.', 'P2_FPL_1'),

('popia', 2, 'Lawful Processing - Eight Conditions', 'Further Processing Limitation', 9, 'Are data subjects informed of significant further processing of their personal information?', 'Section 11(3) requires data subjects to be informed of further processing that significantly differs from the original purpose, unless consented or authorised.', 'POPIA Section 11(3) further processing; ISO 27701 cl.7.2.2 purpose specification', 'High', 'Communication records with data subjects; notification templates; consent records for further processing; privacy notice updates.', 'Develop communication process for significant further processing. Notify data subjects and obtain consent where required. Update privacy notices accordingly.', 'P2_FPL_2'),

-- Condition 5: Information Quality (2 questions)
('popia', 2, 'Lawful Processing - Eight Conditions', 'Information Quality', 10, 'Are there processes in place to ensure personal information is kept accurate and complete?', 'Section 10 information quality requires organisations to take reasonable steps to ensure personal information is complete, accurate, not misleading, and updated.', 'POPIA Section 10 information quality; ISO 27701 cl.7.2.3 data accuracy', 'Critical', 'Data quality procedures; data validation rules; update schedules; error correction processes; data subject request procedures.', 'Implement data quality procedures and validation rules. Establish schedules for data review and updates. Provide easy mechanisms for data subjects to correct inaccuracies.', 'P2_IQ_1'),

('popia', 2, 'Lawful Processing - Eight Conditions', 'Information Quality', 11, 'Does the organisation have a process for responding to data subject requests to correct inaccurate information?', 'Section 10 requires organisations to provide data subjects with the opportunity to correct their personal information where it is inaccurate or incomplete.', 'POPIA Section 10 information quality; ISO 27701 cl.7.2.3 data accuracy', 'High', 'Request handling procedures; response time tracking; update procedures; records of correction requests and responses.', 'Implement data subject request handling process. Track response times and ensure compliance with legal deadlines. Document correction requests and outcomes.', 'P2_IQ_2'),

-- Condition 6: Openness (2 questions)
('popia', 2, 'Lawful Processing - Eight Conditions', 'Openness', 12, 'Is the organisation''s privacy policy publicly available and accessible?', 'Section 18 openness requires organisations to have a privacy policy that is publicly available and accessible to data subjects.', 'POPIA Section 18 openness; ISO 27701 cl.7.2.4 transparency', 'Critical', 'Privacy policy document; publication on website; accessibility features; policy review schedule; version control.', 'Develop comprehensive privacy policy covering all POPIA requirements. Publish on organisation website. Ensure accessibility and maintain version control.', 'P2_OPN_1'),

('popia', 2, 'Lawful Processing - Eight Conditions', 'Openness', 13, 'Does the privacy policy include all required information per POPIA Section 18?', 'Section 18 specifies specific information that must be included in the privacy policy, including the type of personal information processed and the purposes of processing.', 'POPIA Section 18 openness; ISO 27701 cl.7.2.4 transparency', 'High', 'Policy content review checklist; legal review of policy content; update documentation; user feedback on policy clarity.', 'Review policy against Section 18 requirements. Include all required information. Conduct legal review and update based on feedback.', 'P2_OPN_2'),

-- Condition 7: Security Safeguards (3 questions)
('popia', 2, 'Lawful Processing - Eight Conditions', 'Security Safeguards', 14, 'Has the organisation implemented appropriate security measures to protect personal information?', 'Section 19 security safeguards requires organisations to implement appropriate, reasonable technical and organisational measures to prevent security compromises.', 'POPIA Section 19 security safeguards; ISO 27701 cl.6.9–6.13 security measures', 'Critical', 'Security policy and procedures; technical security controls (encryption, access controls); security assessments; incident response plan; security training.', 'Develop comprehensive security programme implementing technical and organisational measures. Conduct regular security assessments. Establish incident response procedures.', 'P2_SEC_1'),

('popia', 2, 'Lawful Processing - Eight Conditions', 'Security Safeguards', 15, 'Are security measures appropriate to the risk level of the personal information being processed?', 'Security measures must be appropriate to the risk level and nature of personal information being processed. This requires a risk-based approach to security.', 'POPIA Section 19 security safeguards; ISO 27701 cl.6.9–6.13 security measures; ISO 27701 cl.6.1.3 risk assessment', 'High', 'Risk assessment methodology; risk register; security control selection process; evidence of risk-based decisions; security testing records.', 'Implement risk assessment methodology. Maintain risk register for personal information processing. Select security controls based on risk level.', 'P2_SEC_2'),

('popia', 2, 'Lawful Processing - Eight Conditions', 'Security Safeguards', 16, 'Is there a documented process for identifying and reporting security compromises?', 'Section 22 requires organisations to identify and report security compromises to the Information Regulator and affected data subjects.', 'POPIA Section 22 security compromises; ISO 27701 cl.6.13.2 incident management', 'Critical', 'Incident detection procedures; incident response plan; reporting procedures; notification templates; contact information for Information Regulator.', 'Implement security incident detection and response procedures. Establish reporting procedures for Information Regulator and data subjects. Maintain incident response plan.', 'P2_SEC_3');