-- Full ~100-task tiered POPIA remediation programme (content only).
-- Source: docs/extracted/Implementation App/PrivacyFramework.html (PHASES array: 6 phases,
-- 20 sections, 108 tasks). 18 prototype tasks are direct duplicates of the 18 seeds from
-- 20260811000006_stage5_tasks.sql and are NOT re-inserted (mapping below); the remaining 90
-- are inserted here, so the full library = 18 seeds + 90 = 108 tasks.
--
-- Tiering: the prototype scopes tasks by COMPANY SIZE tier chosen per client
-- (Tier 1: 5-50 users, Tier 2: 51-100, Tier 3: 101-250). task_templates.tier = the minimum
-- tier at which the task is mandatory (1 = applies to every company; NULL = unclassified,
-- e.g. non-POPIA templates). Tier >1 tasks: MDM (4.2.4) and DLP (4.4.4) from tier 2,
-- annual penetration test (4.5.6) from tier 3, Deputy IO (existing seed) from tier 2.
--
-- Prototype phase/section grouping is preserved: theme = numbered phase title (the board
-- groups and orders by theme text), section context + prototype ref folded into description.
-- responsible/timeframe/output/priority map 1:1 onto the existing columns (priority lowercased).
--
-- Prototype tasks skipped as duplicates of existing seeds (seeds left untouched apart from tier):
--   1.1.1 -> seed 'Appoint & register the Information Officer with the Regulator'
--   1.1.2 -> seed 'Appoint & register the Information Officer with the Regulator'
--   1.1.3 -> seed 'Appoint Deputy Information Officer(s) where required'
--   1.2.3 -> seed 'Establish governance responsibilities & the risk register'
--   2.1.2 -> seed 'Build the Personal Information inventory'
--   2.2.1 -> seed 'Build the Information Asset Register'
--   2.3.2 -> seed 'Set retention periods & the disposal schedule'
--   3.1.2 -> seed 'Publish the PAIA s.51 manual'
--   5.1.3 -> seed 'Deliver POPIA staff awareness training (100%)'
--   5.1.8 -> seed 'Train the Information Officer'
--   5.2.3 -> seed 'Identify operators & issue Operator Agreements (DPAs)'
--   5.2.6 -> seed 'Assess cross-border transfers (s.72)'
--   5.3.1 -> seed 'Publish the Data Subject Request form'
--   5.3.2 -> seed 'Stand up the Data Subject Request process & log'
--   6.1.3 -> seed 'Establish the breach notification workflow (72h) & register'
--   6.1.4 -> seed 'Establish the breach notification workflow (72h) & register'
--   6.2.1 -> seed 'Establish the annual PIMS audit'
--   6.2.6 -> seed 'Submit the PAIA annual report (if required)'
--
-- Idempotency: task_templates has no unique key, so ON CONFLICT has no target; the INSERT
-- uses WHERE NOT EXISTS on (framework_key, title) instead. Content only — no new tables,
-- single minimal ALTER sanctioned for the tier column.

BEGIN;

ALTER TABLE public.task_templates ADD COLUMN IF NOT EXISTS tier int;
COMMENT ON COLUMN public.task_templates.tier IS
  'Minimum company-size tier at which the task is mandatory (1: 5-50 users, 2: 51-100, 3: 101-250). NULL = unclassified.';

-- ---------- tier backfill for the 18 existing POPIA seeds (clear prototype mappings only) ----------
-- ROPA and the quarterly compliance review have no clear prototype counterpart -> tier stays NULL.
UPDATE public.task_templates t
SET tier = v.tier
FROM (VALUES
  ('Appoint & register the Information Officer with the Regulator', 1),
  ('Appoint Deputy Information Officer(s) where required', 2),
  ('Establish governance responsibilities & the risk register', 1),
  ('Build the Personal Information inventory', 1),
  ('Build the Information Asset Register', 1),
  ('Set retention periods & the disposal schedule', 1),
  ('Stand up the Data Subject Request process & log', 1),
  ('Publish the Data Subject Request form', 1),
  ('Establish the breach notification workflow (72h) & register', 1),
  ('Identify operators & issue Operator Agreements (DPAs)', 1),
  ('Assess cross-border transfers (s.72)', 1),
  ('Publish the PAIA s.51 manual', 1),
  ('Submit the PAIA annual report (if required)', 1),
  ('Deliver POPIA staff awareness training (100%)', 1),
  ('Train the Information Officer', 1),
  ('Establish the annual PIMS audit', 1)
) AS v(title, tier)
WHERE t.framework_key = 'popia' AND t.title = v.title AND t.tier IS NULL;

-- ---------- the full tiered library: 90 tasks, 6 phases (privacy track content pack) ----------
INSERT INTO public.task_templates
  (framework_key, content_pack_id, theme, title, description, responsible, timeframe, output, priority, sort, tier)
SELECT 'popia', cp.id, x.theme, x.title, x.description, x.responsible, x.timeframe, x.output, x.priority, x.sort, x.tier
FROM (SELECT id FROM public.content_packs
      WHERE practice_id IS NULL AND framework_key = 'popia' AND version = 1) cp,
(VALUES
  ('1. Governance & Accountability','Define and document the IO''s role, responsibilities, and reporting line',
   '[1.1.4] Phase 1 — Governance & Accountability · 1.1 Appoint the Information Officer (IO). Every responsible party under POPIA must designate an Information Officer. For most SMEs this will be the owner, CEO, or a senior manager. The IO must be registered with the Information Regulator.',
   'Owner / IO','Week 2','IO Role Description Document','high',1010,1),
  ('1. Governance & Accountability','Allocate dedicated time and budget for IO duties (minimum 20% of time for Tier 1; dedicated role for Tier 3)',
   '[1.1.5] Phase 1 — Governance & Accountability · 1.1 Appoint the Information Officer (IO). Every responsible party under POPIA must designate an Information Officer. For most SMEs this will be the owner, CEO, or a senior manager. The IO must be registered with the Information Regulator.',
   'Owner','Week 1','Budget Approval / Time Allocation','high',1020,1),
  ('1. Governance & Accountability','Define committee members or governance contacts for Privacy and IT Security',
   '[1.2.1] Phase 1 — Governance & Accountability · 1.2 Establish Privacy & Security Governance Committee. For Tier 1 (micro/small), this may be a single person with defined responsibilities. Tier 2 and Tier 3 should form a small committee with IT, HR, and Operations representation.',
   'IO / Owner','Week 1','Governance Responsibility Matrix','high',1030,1),
  ('1. Governance & Accountability','Schedule recurring governance meeting (monthly for Tier 1 & 2; bi-weekly for Tier 3)',
   '[1.2.2] Phase 1 — Governance & Accountability · 1.2 Establish Privacy & Security Governance Committee. For Tier 1 (micro/small), this may be a single person with defined responsibilities. Tier 2 and Tier 3 should form a small committee with IT, HR, and Operations representation.',
   'IO','Week 2','Meeting calendar + agenda template','medium',1040,1),
  ('1. Governance & Accountability','Define escalation path for security incidents and privacy complaints',
   '[1.2.4] Phase 1 — Governance & Accountability · 1.2 Establish Privacy & Security Governance Committee. For Tier 1 (micro/small), this may be a single person with defined responsibilities. Tier 2 and Tier 3 should form a small committee with IT, HR, and Operations representation.',
   'IO','Week 2','Escalation Flowchart','high',1050,1),
  ('1. Governance & Accountability','Review assessment findings and categorise gaps as Critical / High / Medium / Low',
   '[1.3.1] Phase 1 — Governance & Accountability · 1.3 Scope & Gap Review (Post-Assessment). Using the completed assessment outputs, formally prioritise and assign remediation tasks.',
   'IO / IT','Week 1','Prioritised Gap List','critical',1060,1),
  ('1. Governance & Accountability','Create a Master Implementation Plan spreadsheet with task, owner, deadline, and status columns',
   '[1.3.2] Phase 1 — Governance & Accountability · 1.3 Scope & Gap Review (Post-Assessment). Using the completed assessment outputs, formally prioritise and assign remediation tasks.',
   'IO','Week 1','Master Implementation Plan','critical',1070,1),
  ('1. Governance & Accountability','Brief senior management on findings, obligations, and consequences of non-compliance (fines up to R10 million or 10 years imprisonment under POPIA)',
   '[1.3.3] Phase 1 — Governance & Accountability · 1.3 Scope & Gap Review (Post-Assessment). Using the completed assessment outputs, formally prioritise and assign remediation tasks.',
   'IO','Week 2','Management Briefing Sign-off','high',1080,1),
  ('1. Governance & Accountability','Obtain written management commitment and budget approval for implementation',
   '[1.3.4] Phase 1 — Governance & Accountability · 1.3 Scope & Gap Review (Post-Assessment). Using the completed assessment outputs, formally prioritise and assign remediation tasks.',
   'Owner / CFO','Week 2','Signed Commitment & Budget Approval','high',1090,1),
  ('2. Data Mapping & Asset Register','Conduct data discovery interviews with each department head to identify all personal data collected',
   '[2.1.1] Phase 2 — Data Mapping & Asset Register · 2.1 Build the Personal Information (PI) Inventory. You cannot protect what you do not know you have. Systematically identify all personal information your organisation collects, processes, stores, and shares.',
   'IO / HR / IT','Week 2–3','Departmental Data Discovery Notes','critical',2010,1),
  ('2. Data Mapping & Asset Register','Identify all special personal information categories (health, race, religion, criminal records, biometrics) — these require heightened protection',
   '[2.1.3] Phase 2 — Data Mapping & Asset Register · 2.1 Build the Personal Information (PI) Inventory. You cannot protect what you do not know you have. Systematically identify all personal information your organisation collects, processes, stores, and shares.',
   'IO','Week 3','Special PI Register with justification for processing','critical',2020,1),
  ('2. Data Mapping & Asset Register','Identify all data subjects: employees, customers, suppliers, website visitors, job applicants',
   '[2.1.4] Phase 2 — Data Mapping & Asset Register · 2.1 Build the Personal Information (PI) Inventory. You cannot protect what you do not know you have. Systematically identify all personal information your organisation collects, processes, stores, and shares.',
   'IO / HR','Week 3','Data Subject Category List','high',2030,1),
  ('2. Data Mapping & Asset Register','Map data flows: where data enters, how it moves through the business, where it exits (to third parties, cloud, email, etc.)',
   '[2.1.5] Phase 2 — Data Mapping & Asset Register · 2.1 Build the Personal Information (PI) Inventory. You cannot protect what you do not know you have. Systematically identify all personal information your organisation collects, processes, stores, and shares.',
   'IO / IT','Week 3–4','Data Flow Diagram','high',2040,1),
  ('2. Data Mapping & Asset Register','For each asset record: system name, owner, data type, location, retention period, and access rights',
   '[2.2.2] Phase 2 — Data Mapping & Asset Register · 2.2 Build the Information Asset Register. List all systems, applications, and databases that store or process personal information and classify each by sensitivity.',
   'IT','Week 4','Completed Asset Register (all fields populated)','high',2050,1),
  ('2. Data Mapping & Asset Register','Classify each asset by sensitivity: Public / Internal / Confidential / Restricted',
   '[2.2.3] Phase 2 — Data Mapping & Asset Register · 2.2 Build the Information Asset Register. List all systems, applications, and databases that store or process personal information and classify each by sensitivity.',
   'IO / IT','Week 4','Asset Classification Labels applied','high',2060,1),
  ('2. Data Mapping & Asset Register','Identify assets that are end-of-life, unpatched, or unsupported — flag for remediation',
   '[2.2.4] Phase 2 — Data Mapping & Asset Register · 2.2 Build the Information Asset Register. List all systems, applications, and databases that store or process personal information and classify each by sensitivity.',
   'IT','Week 4','EOL Asset Risk List','high',2070,1),
  ('2. Data Mapping & Asset Register','Document who has access to each system and whether access rights are appropriate (least privilege)',
   '[2.2.5] Phase 2 — Data Mapping & Asset Register · 2.2 Build the Information Asset Register. List all systems, applications, and databases that store or process personal information and classify each by sensitivity.',
   'IT','Week 4–5','Access Rights Matrix','high',2080,1),
  ('2. Data Mapping & Asset Register','Document the lawful basis for processing each PI category under POPIA (consent, contractual necessity, legal obligation, legitimate interest)',
   '[2.3.1] Phase 2 — Data Mapping & Asset Register · 2.3 Lawful Basis and Retention Rules. For each PI category, document the lawful basis for processing and set retention periods with secure deletion plans.',
   'IO','Week 4–5','Lawful Basis Register','critical',2090,1),
  ('2. Data Mapping & Asset Register','Identify personal information held beyond its retention period and schedule for secure deletion',
   '[2.3.3] Phase 2 — Data Mapping & Asset Register · 2.3 Lawful Basis and Retention Rules. For each PI category, document the lawful basis for processing and set retention periods with secure deletion plans.',
   'IT / IO','Week 5','Data Purge Plan with completion date','high',2100,1),
  ('2. Data Mapping & Asset Register','Document cross-border data transfers (if any cloud services, offshore processors, or international clients exist)',
   '[2.3.4] Phase 2 — Data Mapping & Asset Register · 2.3 Lawful Basis and Retention Rules. For each PI category, document the lawful basis for processing and set retention periods with secure deletion plans.',
   'IO / IT','Week 5','Cross-Border Transfer Register','medium',2110,1),
  ('3. Policy & Documentation Framework','Draft and adopt a Privacy Policy (external-facing) covering what data is collected, why, how long kept, data subject rights, and IO contact. Publish on website.',
   '[3.1.1] Phase 3 — Policy & Documentation Framework · 3.1 Privacy Policies (POPIA Required). POPIA requires documented policies that must be approved by management, communicated to staff, and reviewed annually.',
   'IO / Legal','Week 4–6','Approved Privacy Policy (published)','critical',3010,1),
  ('3. Policy & Documentation Framework','Draft a Privacy Notice for employees covering HR data, payroll, monitoring, and surveillance',
   '[3.1.3] Phase 3 — Policy & Documentation Framework · 3.1 Privacy Policies (POPIA Required). POPIA requires documented policies that must be approved by management, communicated to staff, and reviewed annually.',
   'IO / HR','Week 5–6','Employee Privacy Notice — signed by all staff','critical',3020,1),
  ('3. Policy & Documentation Framework','Draft an Internal Privacy Policy covering data minimisation, staff data handling obligations, and breach reporting duties',
   '[3.1.4] Phase 3 — Policy & Documentation Framework · 3.1 Privacy Policies (POPIA Required). POPIA requires documented policies that must be approved by management, communicated to staff, and reviewed annually.',
   'IO','Week 6–7','Signed Internal Privacy Policy','high',3030,1),
  ('3. Policy & Documentation Framework','Create a Consent Management Process — when and how to obtain valid POPIA consent, consent withdrawal process, and consent records',
   '[3.1.5] Phase 3 — Policy & Documentation Framework · 3.1 Privacy Policies (POPIA Required). POPIA requires documented policies that must be approved by management, communicated to staff, and reviewed annually.',
   'IO / Sales / IT','Week 6–8','Consent Form Templates + Consent Register','high',3040,1),
  ('3. Policy & Documentation Framework','Create a Data Subject Rights Procedure — how to handle access, correction, deletion, and objection requests within POPIA''s 30-day obligation',
   '[3.1.6] Phase 3 — Policy & Documentation Framework · 3.1 Privacy Policies (POPIA Required). POPIA requires documented policies that must be approved by management, communicated to staff, and reviewed annually.',
   'IO','Week 7–8','DSR Procedure Document + Request Form','high',3050,1),
  ('3. Policy & Documentation Framework','Draft and adopt an Information Security Policy (master policy) covering acceptable use, classification, access control, and incident reporting',
   '[3.2.1] Phase 3 — Policy & Documentation Framework · 3.2 Cybersecurity Policies. A complete suite of cybersecurity policies covering all aspects of information security, acceptable use, and incident response.',
   'IO / IT','Week 5–7','Signed Information Security Policy','critical',3060,1),
  ('3. Policy & Documentation Framework','Draft an Acceptable Use Policy (AUP) for all devices, internet use, email, and social media — all staff must sign',
   '[3.2.2] Phase 3 — Policy & Documentation Framework · 3.2 Cybersecurity Policies. A complete suite of cybersecurity policies covering all aspects of information security, acceptable use, and incident response.',
   'IT / HR','Week 5–6','Signed AUP — all staff (filed in HR)','critical',3070,1),
  ('3. Policy & Documentation Framework','Draft a Password and Access Management Policy covering minimum password requirements, MFA mandate, shared account prohibition, and password manager use',
   '[3.2.3] Phase 3 — Policy & Documentation Framework · 3.2 Cybersecurity Policies. A complete suite of cybersecurity policies covering all aspects of information security, acceptable use, and incident response.',
   'IT','Week 6','Password Policy (published in IT handbook)','critical',3080,1),
  ('3. Policy & Documentation Framework','Draft a Remote Work and BYOD Policy covering VPN use, device encryption, screen lock, and home network security',
   '[3.2.4] Phase 3 — Policy & Documentation Framework · 3.2 Cybersecurity Policies. A complete suite of cybersecurity policies covering all aspects of information security, acceptable use, and incident response.',
   'IT / HR','Week 6–7','Remote Work / BYOD Policy — staff signed','high',3090,1),
  ('3. Policy & Documentation Framework','Draft an Incident Response Policy — define what constitutes an incident, response steps, reporting obligations (notify IR within 72 hours), and post-incident review',
   '[3.2.5] Phase 3 — Policy & Documentation Framework · 3.2 Cybersecurity Policies. A complete suite of cybersecurity policies covering all aspects of information security, acceptable use, and incident response.',
   'IO / IT','Week 7–8','IR Policy + IR Playbook (step-by-step)','critical',3100,1),
  ('3. Policy & Documentation Framework','Draft a Backup and Recovery Policy covering backup frequency, offsite/cloud backup, retention, and restoration testing schedule',
   '[3.2.6] Phase 3 — Policy & Documentation Framework · 3.2 Cybersecurity Policies. A complete suite of cybersecurity policies covering all aspects of information security, acceptable use, and incident response.',
   'IT','Week 7','Backup Policy (aligned to recovery objectives)','high',3110,1),
  ('3. Policy & Documentation Framework','Draft a Patch Management Policy covering update frequency for OS, applications, and firmware (critical patches within 72 hours)',
   '[3.2.7] Phase 3 — Policy & Documentation Framework · 3.2 Cybersecurity Policies. A complete suite of cybersecurity policies covering all aspects of information security, acceptable use, and incident response.',
   'IT','Week 7','Patch Policy with maintenance window schedule','high',3120,1),
  ('3. Policy & Documentation Framework','Draft a Third-Party / Supplier Security Policy governing how vendors access your systems and data',
   '[3.2.8] Phase 3 — Policy & Documentation Framework · 3.2 Cybersecurity Policies. A complete suite of cybersecurity policies covering all aspects of information security, acceptable use, and incident response.',
   'IO / Procurement','Week 8','Third-Party Security Policy','high',3130,1),
  ('3. Policy & Documentation Framework','Create a Clean Desk and Screen Lock Policy — physical security of printed data and unattended devices',
   '[3.2.9] Phase 3 — Policy & Documentation Framework · 3.2 Cybersecurity Policies. A complete suite of cybersecurity policies covering all aspects of information security, acceptable use, and incident response.',
   'IO / HR','Week 6','Clean Desk Policy communicated to all staff','medium',3140,1),
  ('3. Policy & Documentation Framework','Create a Policy Register listing all policies, their owners, version numbers, approval dates, and next review dates',
   '[3.3.1] Phase 3 — Policy & Documentation Framework · 3.3 Policy Management Process. Establish a Policy Register and review cycle to ensure all policies remain current and acknowledged by staff.',
   'IO','Week 8','Policy Register (maintained centrally)','high',3150,1),
  ('3. Policy & Documentation Framework','Define policy review cycle — annual review for all policies, triggered review after any incident or regulatory change',
   '[3.3.2] Phase 3 — Policy & Documentation Framework · 3.3 Policy Management Process. Establish a Policy Register and review cycle to ensure all policies remain current and acknowledged by staff.',
   'IO','Week 8','Policy Review Calendar','medium',3160,1),
  ('3. Policy & Documentation Framework','Obtain management sign-off on all policies and file signed copies',
   '[3.3.3] Phase 3 — Policy & Documentation Framework · 3.3 Policy Management Process. Establish a Policy Register and review cycle to ensure all policies remain current and acknowledged by staff.',
   'Owner / IO','Week 8','Signed policy archive (digital + hard copy)','high',3170,1),
  ('3. Policy & Documentation Framework','Distribute all applicable policies to staff and obtain signed acknowledgements — file in HR records',
   '[3.3.4] Phase 3 — Policy & Documentation Framework · 3.3 Policy Management Process. Establish a Policy Register and review cycle to ensure all policies remain current and acknowledged by staff.',
   'HR / IO','Week 8–10','Staff policy acknowledgement log (100% of staff)','critical',3180,1),
  ('4. Technical Controls Implementation','Audit all user accounts across all systems — remove orphan accounts, ex-staff accounts, and shared accounts immediately',
   '[4.1.1] Phase 4 — Technical Controls Implementation · 4.1 Identity & Access Management. Controls that prevent the most common attack vectors: unauthorised access, credential theft, and privilege escalation.',
   'IT','Week 6–7','User Account Audit Report + Remediation Log','critical',4010,1),
  ('4. Technical Controls Implementation','Implement Multi-Factor Authentication (MFA) on all email accounts, remote access (VPN, RDP), and any cloud portals',
   '[4.1.2] Phase 4 — Technical Controls Implementation · 4.1 Identity & Access Management. Controls that prevent the most common attack vectors: unauthorised access, credential theft, and privilege escalation.',
   'IT','Week 6–8','MFA enabled — 100% of accounts confirmed','critical',4020,1),
  ('4. Technical Controls Implementation','Deploy a Password Manager (e.g. Bitwarden, 1Password) for all staff and enforce minimum 14-character unique passwords',
   '[4.1.3] Phase 4 — Technical Controls Implementation · 4.1 Identity & Access Management. Controls that prevent the most common attack vectors: unauthorised access, credential theft, and privilege escalation.',
   'IT','Week 7–8','Password Manager deployed — all staff onboarded','high',4030,1),
  ('4. Technical Controls Implementation','Implement Role-Based Access Control (RBAC) — users must only have access to systems and data required for their role',
   '[4.1.4] Phase 4 — Technical Controls Implementation · 4.1 Identity & Access Management. Controls that prevent the most common attack vectors: unauthorised access, credential theft, and privilege escalation.',
   'IT','Week 7–9','RBAC matrix implemented and documented','high',4040,1),
  ('4. Technical Controls Implementation','Establish a User Provisioning and De-provisioning Process — accounts created/revoked within 24 hours of HR trigger',
   '[4.1.5] Phase 4 — Technical Controls Implementation · 4.1 Identity & Access Management. Controls that prevent the most common attack vectors: unauthorised access, credential theft, and privilege escalation.',
   'IT / HR','Week 8','Onboarding/Offboarding IT Checklist (HR integrated)','critical',4050,1),
  ('4. Technical Controls Implementation','Review and restrict administrative (admin) privileges — no standard users should have local admin rights unless documented',
   '[4.1.6] Phase 4 — Technical Controls Implementation · 4.1 Identity & Access Management. Controls that prevent the most common attack vectors: unauthorised access, credential theft, and privilege escalation.',
   'IT','Week 7','Admin Rights Audit Report','high',4060,1),
  ('4. Technical Controls Implementation','Deploy enterprise-grade Endpoint Detection & Response (EDR) / antivirus on ALL devices (Windows, Mac, mobile) — confirm 100% coverage',
   '[4.2.1] Phase 4 — Technical Controls Implementation · 4.2 Endpoint Protection. Every device that touches company data must be protected, encrypted, and managed.',
   'IT','Week 6–8','EDR Deployment Report (device list + confirmation)','critical',4070,1),
  ('4. Technical Controls Implementation','Enable and enforce automatic OS updates and security patches on all endpoints within defined patch policy windows',
   '[4.2.2] Phase 4 — Technical Controls Implementation · 4.2 Endpoint Protection. Every device that touches company data must be protected, encrypted, and managed.',
   'IT','Week 7','Auto-update enabled — patch compliance report','critical',4080,1),
  ('4. Technical Controls Implementation','Enable Full Disk Encryption on all laptops and mobile devices (BitLocker for Windows; FileVault for Mac; MDM-enforced for mobiles)',
   '[4.2.3] Phase 4 — Technical Controls Implementation · 4.2 Endpoint Protection. Every device that touches company data must be protected, encrypted, and managed.',
   'IT','Week 8–10','Encryption confirmation list per device','high',4090,1),
  ('4. Technical Controls Implementation','Implement Mobile Device Management (MDM) for all company-owned and BYOD devices (Tier 2 & 3: mandatory; Tier 1: strongly recommended)',
   '[4.2.4] Phase 4 — Technical Controls Implementation · 4.2 Endpoint Protection. Every device that touches company data must be protected, encrypted, and managed.',
   'IT','Week 9–12','MDM enrolled — all applicable devices','high',4100,2),
  ('4. Technical Controls Implementation','Disable USB/removable storage ports via Group Policy or MDM unless business-critical use is approved and logged',
   '[4.2.5] Phase 4 — Technical Controls Implementation · 4.2 Endpoint Protection. Every device that touches company data must be protected, encrypted, and managed.',
   'IT','Week 8','USB policy enforced — GPO/MDM configuration saved','medium',4110,1),
  ('4. Technical Controls Implementation','Enable device screen lock (maximum 5 minute timeout) on all devices via policy enforcement',
   '[4.2.6] Phase 4 — Technical Controls Implementation · 4.2 Endpoint Protection. Every device that touches company data must be protected, encrypted, and managed.',
   'IT','Week 7','Screen lock GPO/MDM policy active','high',4120,1),
  ('4. Technical Controls Implementation','Install and configure a Next-Generation Firewall (NGFW) between internet and internal network — enable logging',
   '[4.3.1] Phase 4 — Technical Controls Implementation · 4.3 Network Security. Secure the perimeter, segment internal traffic, and protect email — the most common attack vector.',
   'IT','Week 6–8','Firewall installed, configured, and log retention set','critical',4130,1),
  ('4. Technical Controls Implementation','Segment the network: separate guest Wi-Fi (completely isolated), staff network, and server/finance VLAN',
   '[4.3.2] Phase 4 — Technical Controls Implementation · 4.3 Network Security. Secure the perimeter, segment internal traffic, and protect email — the most common attack vector.',
   'IT','Week 8–10','Network segmentation diagram + VLAN config','high',4140,1),
  ('4. Technical Controls Implementation','Change all default router/switch/firewall credentials. Disable UPnP, unused ports, and remote management unless needed',
   '[4.3.3] Phase 4 — Technical Controls Implementation · 4.3 Network Security. Secure the perimeter, segment internal traffic, and protect email — the most common attack vector.',
   'IT','Week 6','Network device hardening checklist completed','critical',4150,1),
  ('4. Technical Controls Implementation','Implement DNS filtering (e.g. Cisco Umbrella, Cloudflare Gateway, NextDNS) to block malicious domains',
   '[4.3.4] Phase 4 — Technical Controls Implementation · 4.3 Network Security. Secure the perimeter, segment internal traffic, and protect email — the most common attack vector.',
   'IT','Week 8','DNS filtering active — block list report','high',4160,1),
  ('4. Technical Controls Implementation','Deploy a VPN solution for all remote access — prohibit direct RDP/SSH exposure to the internet',
   '[4.3.5] Phase 4 — Technical Controls Implementation · 4.3 Network Security. Secure the perimeter, segment internal traffic, and protect email — the most common attack vector.',
   'IT','Week 8–10','VPN deployed — remote access audit confirms no direct exposure','critical',4170,1),
  ('4. Technical Controls Implementation','Enable email security: SPF, DKIM, and DMARC records on all company email domains to prevent spoofing',
   '[4.3.6] Phase 4 — Technical Controls Implementation · 4.3 Network Security. Secure the perimeter, segment internal traffic, and protect email — the most common attack vector.',
   'IT','Week 7','SPF/DKIM/DMARC DNS records verified (use MXToolbox)','critical',4180,1),
  ('4. Technical Controls Implementation','Implement anti-phishing and email filtering at the gateway level (Microsoft Defender for M365; Google Workspace security; or Proofpoint)',
   '[4.3.7] Phase 4 — Technical Controls Implementation · 4.3 Network Security. Secure the perimeter, segment internal traffic, and protect email — the most common attack vector.',
   'IT','Week 7–9','Email filter configuration report + test results','critical',4190,1),
  ('4. Technical Controls Implementation','Implement the 3-2-1 backup rule: 3 copies of data, on 2 different media types, with 1 offsite (cloud or physical offsite)',
   '[4.4.1] Phase 4 — Technical Controls Implementation · 4.4 Data Protection & Backup. Ensure business continuity and data integrity with proven backup strategies and data loss prevention.',
   'IT','Week 7–9','Backup configuration documentation + test restore log','critical',4200,1),
  ('4. Technical Controls Implementation','Test backup restore monthly — document test date, data restored, time taken, and result. Never assume backups work without testing.',
   '[4.4.2] Phase 4 — Technical Controls Implementation · 4.4 Data Protection & Backup. Ensure business continuity and data integrity with proven backup strategies and data loss prevention.',
   'IT','Ongoing (monthly)','Monthly Backup Restore Test Log','critical',4210,1),
  ('4. Technical Controls Implementation','Encrypt all backups at rest and in transit — confirm encryption keys are stored separately from backup data',
   '[4.4.3] Phase 4 — Technical Controls Implementation · 4.4 Data Protection & Backup. Ensure business continuity and data integrity with proven backup strategies and data loss prevention.',
   'IT','Week 8','Backup encryption confirmation','high',4220,1),
  ('4. Technical Controls Implementation','Implement DLP controls — block emailing bulk personal data externally; block uploading to personal cloud storage (Tier 2 & 3)',
   '[4.4.4] Phase 4 — Technical Controls Implementation · 4.4 Data Protection & Backup. Ensure business continuity and data integrity with proven backup strategies and data loss prevention.',
   'IT','Week 10–12','DLP policy configured in M365/Google Workspace','medium',4230,2),
  ('4. Technical Controls Implementation','Apply retention controls — configure systems to automatically flag or delete data per the Retention Schedule from Phase 2',
   '[4.4.5] Phase 4 — Technical Controls Implementation · 4.4 Data Protection & Backup. Ensure business continuity and data integrity with proven backup strategies and data loss prevention.',
   'IT / IO','Week 10–12','Retention automation configured or manual process confirmed','medium',4240,1),
  ('4. Technical Controls Implementation','Enable centralised logging for: firewall, email gateway, authentication events, and file access on servers (minimum 90-day retention)',
   '[4.5.1] Phase 4 — Technical Controls Implementation · 4.5 Logging, Monitoring & Vulnerability Management. Establish visibility across your environment and actively hunt for vulnerabilities.',
   'IT','Week 8–10','Logging configuration — minimum 90-day retention','high',4250,1),
  ('4. Technical Controls Implementation','Set up alerts for: multiple failed logins, after-hours access, admin account changes, large data transfers',
   '[4.5.2] Phase 4 — Technical Controls Implementation · 4.5 Logging, Monitoring & Vulnerability Management. Establish visibility across your environment and actively hunt for vulnerabilities.',
   'IT','Week 9–10','Alert rules configured — test each alert fires correctly','high',4260,1),
  ('4. Technical Controls Implementation','Conduct a vulnerability scan on all internet-facing systems and internal servers (e.g. Tenable Nessus Essentials, OpenVAS)',
   '[4.5.3] Phase 4 — Technical Controls Implementation · 4.5 Logging, Monitoring & Vulnerability Management. Establish visibility across your environment and actively hunt for vulnerabilities.',
   'IT','Week 8–9','Vulnerability Scan Report','high',4270,1),
  ('4. Technical Controls Implementation','Remediate all Critical vulnerabilities within 72 hours and High vulnerabilities within 30 days — document all actions taken',
   '[4.5.4] Phase 4 — Technical Controls Implementation · 4.5 Logging, Monitoring & Vulnerability Management. Establish visibility across your environment and actively hunt for vulnerabilities.',
   'IT','Per scan cadence','Vulnerability Remediation Tracker','critical',4280,1),
  ('4. Technical Controls Implementation','Schedule quarterly vulnerability scans as a recurring task — add to IT calendar',
   '[4.5.5] Phase 4 — Technical Controls Implementation · 4.5 Logging, Monitoring & Vulnerability Management. Establish visibility across your environment and actively hunt for vulnerabilities.',
   'IT','Ongoing (quarterly)','Quarterly scan reports filed','high',4290,1),
  ('4. Technical Controls Implementation','Conduct an annual penetration test for Tier 3 (101–250 users) and any company processing large volumes of payment card or health data',
   '[4.5.6] Phase 4 — Technical Controls Implementation · 4.5 Logging, Monitoring & Vulnerability Management. Establish visibility across your environment and actively hunt for vulnerabilities.',
   'IT / External vendor','Month 5–6','Penetration Test Report + Remediation Plan','medium',4300,3),
  ('5. Training, Awareness & Third-Party Mgmt','Develop or procure a Privacy Awareness Training Programme covering: what is personal information, staff obligations under POPIA, recognising a privacy breach, and how to report',
   '[5.1.1] Phase 5 — Training, Awareness & Third-Party Mgmt · 5.1 Staff Privacy & Security Training. Human error is the leading cause of data breaches in South African SMEs. Formal training programmes are mandatory under POPIA.',
   'IO / HR','Week 8–10','Training materials or LMS course ready','critical',5010,1),
  ('5. Training, Awareness & Third-Party Mgmt','Develop or procure a Cybersecurity Awareness Training Programme covering: phishing recognition, password hygiene, safe browsing, social engineering, and device security',
   '[5.1.2] Phase 5 — Training, Awareness & Third-Party Mgmt · 5.1 Staff Privacy & Security Training. Human error is the leading cause of data breaches in South African SMEs. Formal training programmes are mandatory under POPIA.',
   'IT / HR','Week 8–10','Training materials or LMS course ready','critical',5020,1),
  ('5. Training, Awareness & Third-Party Mgmt','Conduct a simulated phishing test (e.g. GoPhish, Microsoft Attack Simulator, KnowBe4 free tier) to assess actual staff susceptibility',
   '[5.1.4] Phase 5 — Training, Awareness & Third-Party Mgmt · 5.1 Staff Privacy & Security Training. Human error is the leading cause of data breaches in South African SMEs. Formal training programmes are mandatory under POPIA.',
   'IT','Week 12–14','Phishing simulation report — click rate and remediation actions','high',5030,1),
  ('5. Training, Awareness & Third-Party Mgmt','Provide targeted follow-up training for staff who failed phishing simulations or reported policy violations',
   '[5.1.5] Phase 5 — Training, Awareness & Third-Party Mgmt · 5.1 Staff Privacy & Security Training. Human error is the leading cause of data breaches in South African SMEs. Formal training programmes are mandatory under POPIA.',
   'IT / HR','Within 1 week of test','Individual training completion confirmation','high',5040,1),
  ('5. Training, Awareness & Third-Party Mgmt','Schedule annual refresher training and quarterly security awareness communications (newsletters, screen savers, reminders)',
   '[5.1.6] Phase 5 — Training, Awareness & Third-Party Mgmt · 5.1 Staff Privacy & Security Training. Human error is the leading cause of data breaches in South African SMEs. Formal training programmes are mandatory under POPIA.',
   'IO / HR','Ongoing (annual + quarterly)','Training calendar + communications schedule','medium',5050,1),
  ('5. Training, Awareness & Third-Party Mgmt','Deliver specialised training for IT staff covering incident response, vulnerability management, and technical security controls',
   '[5.1.7] Phase 5 — Training, Awareness & Third-Party Mgmt · 5.1 Staff Privacy & Security Training. Human error is the leading cause of data breaches in South African SMEs. Formal training programmes are mandatory under POPIA.',
   'IT Manager','Month 3–4','IT team training records','high',5060,1),
  ('5. Training, Awareness & Third-Party Mgmt','Compile a Supplier / Operator Register listing all third parties with access to your personal information or systems (cloud providers, payroll processors, accountants, IT support, marketing platforms)',
   '[5.2.1] Phase 5 — Training, Awareness & Third-Party Mgmt · 5.2 Third-Party & Supplier Management. Any operator that processes personal information on your behalf is bound by POPIA. You must have written contracts and conduct due diligence on all such suppliers.',
   'IO / Procurement','Week 8–10','Supplier Register (name, data accessed, contract status)','critical',5070,1),
  ('5. Training, Awareness & Third-Party Mgmt','Review all existing supplier contracts — identify those lacking data protection / operator clauses required by POPIA Section 20 & 21',
   '[5.2.2] Phase 5 — Training, Awareness & Third-Party Mgmt · 5.2 Third-Party & Supplier Management. Any operator that processes personal information on your behalf is bound by POPIA. You must have written contracts and conduct due diligence on all such suppliers.',
   'IO / Legal','Week 9–11','Contract Gap Analysis','critical',5080,1),
  ('5. Training, Awareness & Third-Party Mgmt','Conduct a security questionnaire or review for all critical suppliers (those processing sensitive PI, financial data, or with system access)',
   '[5.2.4] Phase 5 — Training, Awareness & Third-Party Mgmt · 5.2 Third-Party & Supplier Management. Any operator that processes personal information on your behalf is bound by POPIA. You must have written contracts and conduct due diligence on all such suppliers.',
   'IO / IT','Week 12–16','Supplier security assessment completed and filed','high',5090,1),
  ('5. Training, Awareness & Third-Party Mgmt','Establish a process to review new suppliers before onboarding — include data protection assessment as a procurement gate',
   '[5.2.5] Phase 5 — Training, Awareness & Third-Party Mgmt · 5.2 Third-Party & Supplier Management. Any operator that processes personal information on your behalf is bound by POPIA. You must have written contracts and conduct due diligence on all such suppliers.',
   'IO / Procurement','Week 12','Supplier Onboarding Checklist (privacy & security gate)','high',5100,1),
  ('5. Training, Awareness & Third-Party Mgmt','Define identity verification procedure for DSRs — verify requester identity before disclosing or deleting data',
   '[5.3.3] Phase 5 — Training, Awareness & Third-Party Mgmt · 5.3 Data Subject Rights Implementation. POPIA grants data subjects rights to access, correct, and delete their personal information. You must respond within 30 days.',
   'IO','Week 10','Identity Verification SOP for DSRs','high',5110,1),
  ('5. Training, Awareness & Third-Party Mgmt','Test the end-to-end DSR process with a mock request before going live — ensure response within 30-day window is feasible',
   '[5.3.4] Phase 5 — Training, Awareness & Third-Party Mgmt · 5.3 Data Subject Rights Implementation. POPIA grants data subjects rights to access, correct, and delete their personal information. You must respond within 30 days.',
   'IO','Week 12','DSR Process Test Report','medium',5120,1),
  ('6. Ongoing Monitoring, Testing & Review','Conduct a tabletop incident response exercise — simulate a ransomware attack or data breach scenario and test the IR playbook',
   '[6.1.1] Phase 6 — Ongoing Monitoring, Testing & Review · 6.1 Incident Response Readiness. Test your incident response capability before you need it. POPIA mandates breach notification to the Information Regulator within 72 hours.',
   'IO / IT','Month 4–5','Tabletop Exercise Report + Lessons Learned','high',6010,1),
  ('6. Ongoing Monitoring, Testing & Review','Maintain the IR playbook and update after each exercise or real incident — ensure all staff know their roles',
   '[6.1.2] Phase 6 — Ongoing Monitoring, Testing & Review · 6.1 Incident Response Readiness. Test your incident response capability before you need it. POPIA mandates breach notification to the Information Regulator within 72 hours.',
   'IO / IT','Ongoing (annual)','Updated IR Playbook (version controlled)','high',6020,1),
  ('6. Ongoing Monitoring, Testing & Review','Conduct an internal cybersecurity controls review quarterly — check patch status, access rights, backup test results, alert configurations',
   '[6.2.2] Phase 6 — Ongoing Monitoring, Testing & Review · 6.2 Audit, Review & Compliance Monitoring. Regular internal audits and reviews ensure your controls remain effective as your business and the threat landscape evolve.',
   'IT','Quarterly','Quarterly Security Review Report','high',6030,1),
  ('6. Ongoing Monitoring, Testing & Review','Review the Risk Register quarterly — reassess risk ratings, close resolved risks, add new threats, and update treatment plans',
   '[6.2.3] Phase 6 — Ongoing Monitoring, Testing & Review · 6.2 Audit, Review & Compliance Monitoring. Regular internal audits and reviews ensure your controls remain effective as your business and the threat landscape evolve.',
   'IO / IT','Quarterly','Updated Risk Register','high',6040,1),
  ('6. Ongoing Monitoring, Testing & Review','Review the Information Asset Register annually — update for new systems, decommissioned systems, and changed data flows',
   '[6.2.4] Phase 6 — Ongoing Monitoring, Testing & Review · 6.2 Audit, Review & Compliance Monitoring. Regular internal audits and reviews ensure your controls remain effective as your business and the threat landscape evolve.',
   'IT / IO','Annual','Updated Information Asset Register','medium',6050,1),
  ('6. Ongoing Monitoring, Testing & Review','Monitor Information Regulator website and guidance for regulatory updates, new directives, and enforcement notices',
   '[6.2.5] Phase 6 — Ongoing Monitoring, Testing & Review · 6.2 Audit, Review & Compliance Monitoring. Regular internal audits and reviews ensure your controls remain effective as your business and the threat landscape evolve.',
   'IO','Monthly (check)','Regulatory update log','medium',6060,1),
  ('6. Ongoing Monitoring, Testing & Review','After any security incident, conduct a post-incident review within 5 business days — identify root cause, control failures, and corrective actions',
   '[6.3.1] Phase 6 — Ongoing Monitoring, Testing & Review · 6.3 Continuous Improvement. Use every incident, audit finding, and exercise outcome as an opportunity to strengthen your framework.',
   'IO / IT','Within 5 days of incident','Post-Incident Review Report','critical',6070,1),
  ('6. Ongoing Monitoring, Testing & Review','Implement corrective actions from audits, incidents, and exercise reviews within agreed timeframes — track in the Risk Register',
   '[6.3.2] Phase 6 — Ongoing Monitoring, Testing & Review · 6.3 Continuous Improvement. Use every incident, audit finding, and exercise outcome as an opportunity to strengthen your framework.',
   'IO / IT','Ongoing','Corrective Action Tracker (closed-loop)','high',6080,1),
  ('6. Ongoing Monitoring, Testing & Review','Reassess the Privacy Impact Assessment (PIA) for any new project, system, or process that involves significant personal information processing',
   '[6.3.3] Phase 6 — Ongoing Monitoring, Testing & Review · 6.3 Continuous Improvement. Use every incident, audit finding, and exercise outcome as an opportunity to strengthen your framework.',
   'IO','Before launching new projects','Completed PIA for each applicable project','high',6090,1),
  ('6. Ongoing Monitoring, Testing & Review','Benchmark your controls annually against the NIST Cybersecurity Framework or CIS Controls to identify maturity improvements',
   '[6.3.4] Phase 6 — Ongoing Monitoring, Testing & Review · 6.3 Continuous Improvement. Use every incident, audit finding, and exercise outcome as an opportunity to strengthen your framework.',
   'IO / IT','Annual','Annual Maturity Assessment Report','medium',6100,1)
) AS x(theme, title, description, responsible, timeframe, output, priority, sort, tier)
WHERE NOT EXISTS (
  SELECT 1 FROM public.task_templates t
  WHERE t.framework_key = 'popia' AND t.title = x.title
);

COMMIT;
