-- POPIA Assessment Questions - Phase 4 Content Migration
-- This migration adds comprehensive POPIA-specific assessment questions
-- replacing the GDPR baseline with South African regulatory context

-- First, deactivate existing GDPR questions
UPDATE public.assessment_questions SET active = FALSE WHERE framework = 'gdpr';

-- Module 1: Governance and Accountability (12 questions)
INSERT INTO public.assessment_questions (framework, section_id, section_name, subsection, question_number, question, why_matters, regulatory_ref, risk, evidence_req, remediation, uid) VALUES
('popia', 1, 'Governance and Accountability', 'Information Officer Registration', 1, 'Has the organisation appointed a duly authorised Information Officer (IO) in terms of Section 55(1) of POPIA?', 'POPIA requires every organisation to appoint an Information Officer by operation of law. The IO must be registered with the Information Regulator before assuming duties. Failure to appoint and register an IO is a fundamental compliance breach.', 'POPIA Section 55(1)-(2); Information Regulator Guidance Note on Information Officers', 'Critical', 'IO appointment letter or board resolution; IO registration confirmation from Information Regulator eServices portal; registration number and date; IO job description with allocated resources.', 'Appoint an IO via board resolution or formal appointment letter. Register the IO on the Information Regulator eServices portal (www.inforegulator.org.za) and obtain registration number. Document IO duties, responsibilities, and reporting lines.', 'P1_IO_1'),

('popia', 1, 'Governance and Accountability', 'Information Officer Registration', 2, 'Has the organisation appointed a Deputy Information Officer (DIO) where required?', 'Large organisations or those with complex processing operations may require a Deputy IO to assist the primary IO. The DIO supports the IO in fulfilling their statutory duties.', 'POPIA Section 55(3); Information Regulator Guidance', 'High', 'DIO appointment letter; delegation of authority document; DIO job description; evidence of DIO support for IO duties.', 'Assess organisational complexity and processing volume. Appoint DIO if required via formal delegation. Document DIO responsibilities and support mechanisms.', 'P1_IO_2'),

('popia', 1, 'Governance and Accountability', 'Information Officer Registration', 3, 'Is the Information Officer registered with the Information Regulator via the eServices portal?', 'Section 55(2) requires the IO to be registered with the Information Regulator before assuming duties. Registration must be done via the official eServices portal.', 'POPIA Section 55(2); Information Regulator eServices portal', 'Critical', 'Registration confirmation from eServices portal; registration number; registration date; screenshot of registration status.', 'Complete registration on Information Regulator eServices portal. Download and save registration confirmation. Maintain registration number in records.', 'P1_IO_3'),

('popia', 1, 'Governance and Accountability', 'Compliance Framework', 4, 'Has the organisation implemented a documented POPIA compliance framework?', 'A documented compliance framework demonstrates accountability and provides structure for ongoing compliance activities. This is essential for demonstrating compliance under Section 5(2) accountability.', 'POPIA Section 5(2) accountability; ISO 27701 cl.5.1 leadership', 'Critical', 'Compliance framework document; policy and procedure library; governance structure; risk assessment methodology; training programme.', 'Develop comprehensive POPIA compliance framework covering all 8 conditions. Document policies, procedures, and governance structure. Implement risk assessment methodology.', 'P1_CF_1'),

('popia', 1, 'Governance and Accountability', 'Compliance Framework', 5, 'Does the compliance framework include executive-level oversight and board reporting?', 'Board-level oversight ensures senior management commitment and resource allocation for compliance activities. This is required for demonstrating accountability.', 'POPIA Section 5(2) accountability; ISO 27701 cl.9.3 management review', 'High', 'Board meeting minutes showing compliance as agenda item; executive sponsorship documentation; quarterly compliance reports to board; budget allocation for compliance activities.', 'Include compliance as standing board agenda item. Assign executive sponsor. Provide quarterly compliance reports to board. Allocate budget for compliance activities.', 'P1_CF_2'),

('popia', 1, 'Governance and Accountability', 'Compliance Framework', 6, 'Has the organisation conducted and documented a Personal Information Impact Assessment (PIIA)?', 'POPIA requires ongoing PIIA to assess privacy risks and implement appropriate measures. Unlike GDPR DPIA which is for high-risk processing, POPIA expects proactive PIIA as good practice.', 'POPIA Section 24 risk assessment; Information Regulator Guidance on PIIA', 'High', 'PIIA documentation; risk register; PIIA methodology; evidence of PIIA reviews; action plans for identified risks.', 'Develop PIIA methodology aligned to POPIA requirements. Conduct initial PIIA for all processing activities. Document findings and risk treatments. Review PIIA when processing changes.', 'P1_CF_3'),

('popia', 1, 'Governance and Accountability', 'PAIA Manual', 7, 'Has the organisation compiled and published a Section 51 PAIA manual?', 'Section 51 of PAIA requires every private body to compile a manual. The manual must include POPIA processing information and be available to the public.', 'PAIA Section 51; POPIA integration with PAIA requirements', 'Critical', 'Section 51 manual; publication on website; manual content includes POPIA processing information; update procedure for manual.', 'Compile Section 51 manual following Information Regulator guidelines. Include POPIA processing information. Publish on organisation website. Establish update procedure for manual.', 'P1_PAIA_1'),

('popia', 1, 'Governance and Accountability', 'PAIA Manual', 8, 'Does the PAIA manual include all required categories and current information?', 'The PAIA manual must include 8 specific categories and be kept current. Outdated or incomplete manuals are non-compliant.', 'PAIA Section 51; Information Regulator PAIA manual guidelines', 'High', 'Manual content review checklist; update logs; user feedback on manual; evidence of regular reviews.', 'Review manual against Information Regulator checklist. Update all required categories. Implement regular review schedule (minimum annually). Maintain update logs.', 'P1_PAIA_2'),

('popia', 1, 'Governance and Accountability', 'Training and Awareness', 9, 'Does the organisation provide POPIA training to all staff who process personal information?', 'Section 5(2) accountability requires organisations to train staff who process personal information. Untrained staff cannot be expected to comply with POPIA requirements.', 'POPIA Section 5(2) accountability; ISO 27701 cl.7.3 awareness training', 'Critical', 'Training records; training materials; training schedule; attendance registers; assessment of training effectiveness.', 'Develop POPIA training programme targeting all staff who process personal information. Conduct regular training sessions. Maintain training records. Assess training effectiveness.', 'P1_TR_1'),

('popia', 1, 'Governance and Accountability', 'Training and Awareness', 10, 'Is training provided to new employees within their first month of employment?', 'New employees must be trained before they process personal information to ensure compliance from day one.', 'POPIA Section 5(2) accountability; ISO 27701 cl.7.3 awareness training', 'High', 'New hire training programme; onboarding checklist; training records for new hires; induction process documentation.', 'Include POPIA training in onboarding programme. Ensure training completed before new hire processes personal information. Document induction process.', 'P1_TR_2'),

('popia', 1, 'Governance and Accountability', 'Records Management', 11, 'Has the organisation implemented a records management system for POPIA compliance documentation?', 'POPIA requires organisations to maintain records of processing activities. A records management system ensures these records are properly maintained and can be produced when required.', 'POPIA Section 14 documentation; ISO 27701 cl.7.5 records of processing', 'Medium', 'Records management system; document retention schedule; record inventory; backup and recovery procedures.', 'Implement records management system for compliance documentation. Establish retention schedule based on POPIA requirements. Implement backup and recovery procedures.', 'P1_RM_1'),

('popia', 1, 'Governance and Accountability', 'Budget and Resources', 12, 'Are adequate budget and resources allocated for POPIA compliance activities?', 'Compliance requires investment in systems, training, and personnel. Inadequate resources can prevent effective compliance.', 'POPIA Section 5(2) accountability; ISO 27701 cl.5.1 leadership commitment', 'High', 'Annual compliance budget; resource allocation documentation; technology investment plan; personnel plan for compliance function.', 'Develop annual compliance budget. Allocate resources for technology, training, and personnel. Document resource allocation. Review and adjust budget annually.', 'P1_BR_1');