-- POPIA policy template library — full content extraction from the PIM Generator prototype
-- (docs/extracted/PIM Generator/PIM_Generator_Offline.html: STEPS wizard fields + buildDocx
-- document-assembly sections). Pure content: INSERTs only, zero schema change.
--
-- Attaches to the existing global POPIA content pack (version 1), same pattern as the
-- 20260811000003 starter seeds. The 5 starter skeletons (privacy_policy, retention_schedule,
-- dsr_procedure, breach_procedure, internal_privacy_policy) are left untouched; this adds
-- 21 NEW templates for the remaining checklist slots, grounded in the prototype text.
-- Placeholder convention matches the existing seeds: [PLACEHOLDER] markers in markdown.

BEGIN;

INSERT INTO public.policy_templates (framework_key, content_pack_id, slot_key, name, body)
SELECT 'popia', cp.id, x.slot_key, x.name, x.body
FROM (SELECT id FROM public.content_packs WHERE practice_id IS NULL AND framework_key='popia' AND version=1) cp,
(VALUES

  -- ── Phase 1 — Governance & accountability ──────────────────────────────────

  ('io_appointment','Information Officer Appointment Letter',
E'# Information Officer Appointment Letter\n\n**[ORGANISATION NAME]** (Reg. No. [REGISTRATION NUMBER])\n[PHYSICAL ADDRESS]\n\nDate: [DATE]\n\n## Designation\nIn terms of s.55 of the Protection of Personal Information Act, 2013 (POPIA), read with s.17 of the Promotion of Access to Information Act, 2000 (PAIA), the [APPROVAL AUTHORITY] of [ORGANISATION NAME] hereby designates:\n\n| | |\n|---|---|\n| Name | [IO NAME] |\n| Title / designation | [IO TITLE] |\n| Email | [IO EMAIL] |\n| Telephone | [IO PHONE] |\n\nas its **Information Officer**, with effect from [DATE].\n\n## Responsibilities (POPIA s.55)\nThe Information Officer is responsible for:\n- Encouraging and ensuring the organisation''s compliance with the conditions for lawful processing;\n- Dealing with requests made to the organisation under POPIA and PAIA;\n- Working with the Information Regulator in relation to investigations;\n- Ensuring this designation is registered with the Information Regulator before duties are taken up;\n- Otherwise ensuring compliance with POPIA and the organisation''s Privacy Information Manual.\n\nAll data subject requests must be submitted to the Information Officer at the contact details above and are acknowledged within 3 business days.\n\n## Acceptance\nSigned (Information Officer): ______________________  Date: [DATE]\n\nSigned ([APPROVAL AUTHORITY]): ______________________  Date: [DATE]'),

  ('io_registration','Information Regulator Registration Record',
E'# Information Regulator Registration Record\n\nPOPIA s.55(2) requires the Information Officer to be registered with the Information Regulator (South Africa) before taking up duties.\n\n| | |\n|---|---|\n| Organisation | [ORGANISATION NAME] |\n| Information Officer | [IO NAME] ([IO EMAIL]) |\n| Registration status | [Registered — IR reference number obtained / Registration in progress / Not yet registered] |\n| IR reference number | [IR REFERENCE NUMBER] |\n| Date registered | [DATE] |\n| Channel | Information Regulator eServices portal |\n\n## Information Regulator contact details\n- Email: inforeg@justice.gov.za\n- Website: www.inforeg.org.za\n- Address: JD House, 27 Stiemens Street, Braamfontein, Johannesburg 2001\n\n_Attach the registration confirmation or proof of submission as evidence. Update on any change of Information Officer._'),

  ('deputy_io','Deputy Information Officer Designation',
E'# Deputy Information Officer Designation\n\nIn terms of POPIA s.56 read with PAIA s.17(3), [ORGANISATION NAME] designates the following Deputy Information Officer(s) to assist the Information Officer, [IO NAME]:\n\n| Deputy IO | Contact | Area of responsibility |\n|---|---|---|\n| [DEPUTY IO NAME] | [DEPUTY IO CONTACT] | [e.g. HR / IT / Operations] |\n\n## Delegated duties\nEach Deputy IO acts under the direction of the Information Officer and may:\n- Receive and process data subject and PAIA requests for their area;\n- Maintain the registers (ROPA, consent register, DSR log, breach register) for their area;\n- Escalate suspected security compromises to the Information Officer immediately.\n\nAccountability under POPIA remains with the organisation and its Information Officer; delegation does not transfer it.\n\nSigned (Deputy IO): ______________________  Date: [DATE]\n\nSigned (Information Officer): ______________________  Date: [DATE]'),

  ('io_role_desc','Information Officer Role Description',
E'# Information Officer Role Description\n\n**Role:** Information Officer, [ORGANISATION NAME] · **Incumbent:** [IO NAME], [IO TITLE]\n**Aligned to:** POPIA s.55-57 · PAIA s.17 · ISO/IEC 27701:2019 cl.5.3\n\n## Purpose\nOwn and drive the organisation''s compliance with POPIA and PAIA, and operate the Privacy Information Management System (PIMS).\n\n## Key duties\n- Encourage and monitor compliance with the eight conditions for lawful processing;\n- Register with the Information Regulator and keep the registration current;\n- Maintain the Privacy Information Manual and the PAIA s.51 Manual;\n- Receive, log and respond to data subject requests (acknowledge within 3 business days; respond within statutory timeframes);\n- Maintain the ROPA, retention schedule, consent records, DSR log and breach register;\n- Lead security compromise response and s.22 notifications to the Regulator and affected data subjects;\n- Oversee operator agreements (s.20-21) and transborder transfer safeguards (s.72);\n- Conduct or commission the annual privacy risk assessment and compliance audit;\n- Report to the [APPROVAL AUTHORITY] on privacy compliance at least [quarterly].\n\n## Authority\nThe Information Officer has authority to access all processing activities and records of the organisation and to require remediation of non-compliant processing.\n\n_Review annually together with the Privacy Information Manual._'),

  ('governance_matrix','Privacy Governance & Accountability Framework',
E'# Privacy Governance & Accountability Framework\n\nPOPIA s.8 makes [ORGANISATION NAME] accountable for ensuring the conditions for lawful processing are complied with. This framework records how that accountability is given effect (ISO 27701 cl.5).\n\n## Accountability measures\n- Designated, registered Information Officer ([IO NAME]);\n- Board-approved Privacy Policy and Privacy Information Manual;\n- PIMS aligned to ISO/IEC 27701:2019;\n- Record of Processing Activities (ROPA), maintained and reviewed;\n- Privacy by Design embedded into new systems and projects;\n- Privacy compliance monitoring and reporting framework.\n\n## Responsibility matrix\n| Responsibility | [APPROVAL AUTHORITY] | Information Officer | Deputy IO(s) | Line managers | All staff |\n|---|---|---|---|---|---|\n| Approve Privacy Policy & Manual | A | R | C | I | I |\n| Registers (ROPA, consent, DSR, breach) | I | A | R | C | I |\n| Data subject requests | I | A | R | C | I |\n| Security compromise response | I | A | R | R | R (report) |\n| Operator agreements (s.20-21) | I | A | C | R | — |\n| Training & awareness | I | A | R | R | R (attend) |\n\nR = responsible · A = accountable · C = consulted · I = informed\n\n## Leadership commitment (ISO 27701 cl.5)\nTop management demonstrates commitment by: approving the Privacy Policy and Manual; appointing and supporting the IO; integrating privacy into business strategy; ensuring adequate resources; and receiving regular compliance reports.\n\n_Owner: Information Officer · Review annually._'),

  ('risk_register','Privacy Risk Register & Impact Assessment Procedure',
E'# Privacy Risk Register & Impact Assessment Procedure\n\nAn annual privacy risk assessment identifies risks to data subject rights (ISO 27701 cl.6). Privacy by Design is applied to new systems, products and services; Privacy Impact Assessments (PIAs) are conducted for high-risk processing activities.\n\n## Register\n| # | Risk | PI / activity affected | Likelihood | Impact | Rating | Owner | Treatment | Target date | Status |\n|---|---|---|---|---|---|---|---|---|---|\n| 1 | [e.g. excessive access to HR records] | [Employee PI] | [M] | [H] | [High] | [Owner] | [Access review, least privilege] | [DATE] | [Open] |\n\n## When a PIA is required\nConduct a PIA before: new systems processing PI at scale; new special-PI or children''s-PI processing; new transborder transfers; large-scale monitoring; or material changes to processing purposes.\n\n## PIA outline\n1. Describe the processing (purpose, PI categories, flows).\n2. Assess necessity, minimality and lawful basis (s.9-12).\n3. Identify risks to data subjects; rate likelihood and impact.\n4. Agree safeguards; residual-risk sign-off by the Information Officer.\n\n_Owner: Information Officer · Reviewed annually and on material change._'),

  -- ── Phase 2 — Data mapping & registers ─────────────────────────────────────

  ('pi_inventory','Record of Processing Activities (ROPA)',
E'# Record of Processing Activities (ROPA)\n\nMaintained by the Information Officer under POPIA s.17 read with s.8 (ISO 27701 cl.7.2); updated whenever processing activities change.\n\n| PI category | Data subjects | Purpose | Legal basis (s.11) | Retention | Shared with / operators | Transborder (s.72) | Security measures |\n|---|---|---|---|---|---|---|---|\n| Customer / client PI | Customers | Service delivery, invoicing, communication | Contract; Consent | 5 years post-contract | [Operators] | [Countries or none] | [Controls] |\n| Employee / HR PI | Employees | Payroll, employment, statutory reporting | Contract; Legal obligation | 7 years post-employment | [Payroll provider] | [ ] | [ ] |\n| Supplier / vendor PI | Supplier contacts | Procurement, payments, communication | Contract; Legitimate interest | 5 years post-contract | [ ] | [ ] | [ ] |\n| Marketing / leads | Prospects | Direct marketing, lead nurturing | Consent; Legitimate interest | Until opt-out + 1 year | [ ] | [ ] | [ ] |\n| Website visitors | Visitors | Analytics, security, user experience | Legitimate interest; Consent | 24 months | [ ] | [ ] | [ ] |\n\n[Add a row for every processing activity. State the specific purpose per category — "business purposes" is insufficient.]\n\n_Owner: Information Officer · Review annually and on any change to processing._'),

  ('special_pi_register','Special & Children''s Personal Information Register',
E'# Special & Children''s Personal Information Register\n\nSpecial personal information (POPIA s.26-33: religious or philosophical beliefs, race or ethnic origin, trade union membership, political persuasion, health or sex life, biometric information, criminal behaviour) and children''s personal information (s.34-35) may only be processed under a specific authorisation.\n\n| PI type | Data subjects | Processing activity | s.27-33 / s.35 authorisation | Safeguards | Owner |\n|---|---|---|---|---|---|\n| [Health information] | [Employees] | [Sick-leave administration] | [s.27 — obligation under employment law] | [Restricted access, encryption] | [HR] |\n\n## Children''s personal information\nStatus: [No — children''s information is not processed / Yes — parental consent mechanism is in place / Yes — a POPIA s.35 exemption applies / Under review]. Where children''s personal information is processed, parental or guardian consent is obtained in terms of POPIA s.35 unless an exemption applies; consent records are kept in the consent register.\n\n_Owner: Information Officer · Review annually._'),

  ('data_subject_categories','Data Subject Categories Register',
E'# Data Subject Categories Register\n\nCategories of data subjects whose personal information [ORGANISATION NAME] processes (supports POPIA s.17 documentation and the ROPA).\n\n| Category | Examples | Main PI processed | Main purposes | Notice given via |\n|---|---|---|---|---|\n| Customers / clients | [Account holders] | Identity, contact, transaction | Service delivery, invoicing | [Privacy Policy on website] |\n| Employees | Current & former staff | Identity, employment, payroll | Payroll, employment, statutory reporting | [Employee Privacy Notice] |\n| Job applicants | [Candidates] | CVs, references | Recruitment | [Application privacy notice] |\n| Suppliers / vendors | Supplier contacts | Contact, banking | Procurement, payments | [Contract clause] |\n| Marketing leads | Prospects | Contact, preferences | Direct marketing (s.69) | [Opt-in form] |\n| Website visitors | Site users | Device, usage | Analytics, security | [Cookie / privacy notice] |\n\n[Add or remove categories to match the ROPA — the two documents must stay aligned.]\n\n_Owner: Information Officer · Review annually._'),

  ('data_flow','Personal Information Flow Map',
E'# Personal Information Flow Map\n\nHow personal information enters, moves through, and leaves [ORGANISATION NAME] (supports the ROPA and POPIA s.17; ISO 27701 cl.7.2).\n\n## 1. Collection points\n| Channel | PI collected | Data subjects | Notice at collection (s.18)? |\n|---|---|---|---|\n| [Website forms] | [Contact details] | [Prospects] | [Yes — privacy notice link] |\n| [Employee onboarding] | [HR records] | [Employees] | [Yes — employee notice] |\n\n## 2. Systems & storage\n| System | PI held | Location (SA / offshore) | Access restricted to |\n|---|---|---|---|\n| [CRM] | [Customer PI] | [SA] | [Sales team] |\n\n## 3. Internal flows\n[Describe movements between departments and systems, e.g. sales to finance for invoicing.]\n\n## 4. External sharing & operators\n[Which operators and third parties receive PI — must match the supplier register and operator agreements (s.20-21).]\n\n## 5. Transborder flows (s.72)\n[Countries PI is transferred to and the s.72 safeguard relied upon, or "South Africa only".]\n\n## 6. Disposal\n[How each store is deleted or de-identified when the retention period expires (s.14) — per the retention schedule.]\n\n_Owner: Information Officer · Review annually and on system changes._'),

  ('lawful_basis_register','Lawful Basis Register (POPIA s.11)',
E'# Lawful Basis Register (POPIA s.11)\n\nEvery processing activity must rest on one of the s.11(1) grounds. State the specific ground per activity — "business purposes" is insufficient.\n\n## s.11(1) grounds\n- (a) Consent of the data subject (or a competent person for a child);\n- (b) Necessary for the conclusion or performance of a contract with the data subject;\n- (c) Compliance with an obligation imposed by law;\n- (d) Protection of a legitimate interest of the data subject;\n- (e) Necessary for the proper performance of a public law duty;\n- (f) Necessary for pursuing the legitimate interests of the organisation or a third party.\n\n## Register\n| Processing activity | PI category | s.11 ground | Justification / notes |\n|---|---|---|---|\n| [Customer service delivery] | [Customer PI] | s.11(1)(b) contract | [Necessary to perform the service contract] |\n| [Payroll] | [Employee PI] | s.11(1)(c) legal obligation | [BCEA / SARS] |\n| [Direct marketing] | [Leads] | s.11(1)(a) consent | [Opt-in recorded; opt-out honoured (s.69)] |\n\nWhere consent is the ground it may be withdrawn at any time, and processing must stop unless another ground applies (s.11(3)). Objections on reasonable grounds are honoured unless processing is required by law.\n\n_Owner: Information Officer · Keep aligned with the ROPA._'),

  ('crossborder_register','Cross-Border Transfer Register (POPIA s.72)',
E'# Cross-Border Transfer Register (POPIA s.72)\n\nPersonal information is transferred outside South Africa only in compliance with POPIA s.72.\n\n| Recipient | Country | PI categories | Purpose | s.72 ground / safeguard | Agreement ref | Review date |\n|---|---|---|---|---|---|---|\n| [Cloud provider] | [Country] | [Customer PI] | [Hosting] | [s.72(1)(a) — binding agreement providing an adequate level of protection] | [Operator agreement] | [DATE] |\n\n[If no PI leaves South Africa, record "South Africa only" and review annually.]\n\n## s.72(1) grounds for transfer\n- (a) The recipient is subject to a law, binding corporate rules or a binding agreement providing an adequate level of protection;\n- (b) The data subject consents to the transfer;\n- (c) The transfer is necessary for the performance of a contract with the data subject;\n- (d) The transfer is necessary for a contract, in the interest of the data subject, between the organisation and a third party;\n- (e) The transfer is for the benefit of the data subject, consent is not reasonably practicable to obtain, and would likely be given.\n\n_Owner: Information Officer · Keep aligned with the supplier register and the data flow map._'),

  -- ── Phase 3 — Policies & notices ───────────────────────────────────────────

  ('paia_manual','PAIA Manual (Section 51)',
E'# PAIA Manual (Section 51)\n\nManual in terms of s.51 of the Promotion of Access to Information Act, 2000 (PAIA), incorporating POPIA information, for **[ORGANISATION NAME]**.\n\n## 1. Organisation details\n| | |\n|---|---|\n| Legal name | [ORGANISATION NAME] |\n| Registration number | [REGISTRATION NUMBER] |\n| Physical address | [PHYSICAL ADDRESS] |\n| Website | [WEBSITE] |\n| Sector / industry | [SECTOR / INDUSTRY] |\n\n## 2. Information Officer\n[IO NAME], [IO TITLE] · [IO EMAIL] · [IO PHONE]. All PAIA requests and data subject requests are submitted to the Information Officer.\n\n## 3. Guide of the Information Regulator (PAIA s.10)\nThe Regulator''s Guide on how to use PAIA is available from the Information Regulator (South Africa): inforeg@justice.gov.za · www.inforeg.org.za · JD House, 27 Stiemens Street, Braamfontein, Johannesburg 2001.\n\n## 4. Categories of records held\n| Category | Description | Availability |\n|---|---|---|\n| Statutory & company records | [CIPC, tax, licences] | On request (PAIA) |\n| Personnel records | [Employment, payroll] | On request (PAIA) |\n| Customer records | [Contracts, transactions] | On request (PAIA) |\n| Operational records | [Policies, correspondence] | On request (PAIA) |\n\n## 5. How to request access\n1. Complete **PAIA Form 2** (Request for Access to Record) and submit it to the Information Officer with proof of identity.\n2. Pay the prescribed request and access fees where applicable.\n3. Requests are acknowledged within 3 business days and decided within **30 days** (extendable to 60 days for complex requests).\n4. If access is refused, grounds are provided; the requester may complain to the Information Regulator or apply to court.\n\n## 6. Processing of personal information (POPIA)\nCategories of PI processed, purposes, recipients, transborder transfers and security measures are documented in the organisation''s Privacy Information Manual and Privacy Policy. Data subjects may request access (s.23), correction or deletion (s.24), and may object to processing (s.11(3)).\n\n_Approved by [APPROVAL AUTHORITY] · Published on [WEBSITE] · Review annually._'),

  ('employee_privacy_notice','Employee Privacy Notice',
E'# Employee Privacy Notice\n\n**[ORGANISATION NAME]** processes personal information of employees in line with POPIA. This notice makes the s.18 disclosures for staff.\n\n## 1. Who we are\n[ORGANISATION NAME], [PHYSICAL ADDRESS]. Information Officer: [IO NAME], [IO EMAIL], [IO PHONE].\n\n## 2. What we process\nIdentity and contact details; employment history and qualifications; payroll, tax and banking details; leave and performance records; [health / disability information for statutory purposes]; [monitoring data, e.g. access logs / CCTV].\n\n## 3. Why, and on what basis (s.11)\n| Purpose | Legal basis |\n|---|---|\n| Payroll and employment administration | Contract (s.11(1)(b)); Legal obligation (s.11(1)(c)) |\n| Statutory reporting (SARS, UIF, COIDA) | Legal obligation |\n| [Benefits administration] | [Contract / consent] |\n| [Security and facilities monitoring] | [Legitimate interest (s.11(1)(f))] |\n\nSupplying this information is mandatory where required for employment or by law; without it we may be unable to employ or pay you.\n\n## 4. Sharing\n[Payroll provider, medical aid, pension fund, SARS and other authorities], under operator agreements (s.20-21) or legal duty.\n\n## 5. Retention\nEmployment records are retained for 7 years post-employment (Basic Conditions of Employment Act; tax legislation), per the Retention Schedule.\n\n## 6. Your rights\nAccess (s.23), correction or deletion (s.24), objection (s.11(3)), and complaint to the Information Regulator (inforeg@justice.gov.za · www.inforeg.org.za). Requests go to the Information Officer and are acknowledged within 3 business days.\n\n## Acknowledgement\nI confirm that I have read and understood this notice.\n\nName: ____________________  Signature: ____________________  Date: [DATE]'),

  ('consent_records','Consent Management Procedure & Register',
E'# Consent Management Procedure & Register\n\nWhere consent is the legal basis (POPIA s.11(1)(a)), it is obtained **before** collection, is **specific and voluntary**, is **recorded with timestamp and wording**, and may be **withdrawn at any time** (s.11(3)).\n\n## Procedure\n1. **Design** — each consent request states the specific purpose in plain language, separate from other terms. Children''s PI requires parental or guardian consent (s.35).\n2. **Capture** — record who consented, when, to which wording version, and through which channel.\n3. **Honour** — process only within the consented purpose. Further processing requires a compatibility assessment (s.15) or fresh consent.\n4. **Withdraw** — provide an easy withdrawal mechanism; stop processing on withdrawal unless another s.11 ground applies. Withdrawal does not affect the lawfulness of prior processing.\n5. **Direct marketing** — electronic direct marketing follows POPIA s.69 and ECTA s.45 (consent-based opt-in with opt-out); opt-outs are actioned immediately.\n\n## Consent register\n| Date / time | Data subject | Channel | Consent wording / version | Purpose | Withdrawn (date) |\n|---|---|---|---|---|---|\n| [timestamp] | [name / id] | [web form] | [v1.0 marketing consent] | [newsletter] | [—] |\n\n_Owner: Information Officer · Consent wording versions are retained as evidence._'),

  -- ── Phase 5 — Third parties & DSR operations ───────────────────────────────

  ('supplier_register','Operator & Supplier Register',
E'# Operator & Supplier Register\n\nAll third parties processing personal information on behalf of [ORGANISATION NAME] are recorded here and bound by written operator agreements (POPIA s.20-21).\n\n| Operator / supplier | Service | PI processed | Agreement (s.20-21) signed | Location / country | Transborder (s.72) safeguard | Security assessed | Review date |\n|---|---|---|---|---|---|---|---|\n| [CloudCo] | [Hosting] | [Customer PI] | [Yes — DATE] | [Country] | [s.72(1)(a) agreement / n/a] | [Yes] | [DATE] |\n| [Payroll provider] | [Payroll] | [Employee PI] | [Yes — DATE] | [SA] | [n/a] | [Yes] | [DATE] |\n\n[Every row must have a signed operator agreement — a missing agreement is a compliance gap.]\n\n_Owner: Information Officer · Keep aligned with the cross-border register and the data flow map · Review annually._'),

  ('operator_agreements','Operator Agreement (POPIA s.20-21)',
E'# Operator Agreement (POPIA s.20-21)\n\nAgreement between **[ORGANISATION NAME]** ("the Responsible Party") and **[OPERATOR NAME]** ("the Operator") governing the processing of personal information by the Operator on behalf of the Responsible Party.\n\n## 1. Scope of processing\n| | |\n|---|---|\n| Services | [Service description] |\n| PI categories | [Categories] |\n| Data subjects | [Categories] |\n| Duration | [Term] |\n\n## 2. Operator obligations\nThe Operator shall:\n1. Process personal information **only on the instruction** of the Responsible Party and only for the purposes above (s.20);\n2. Treat all personal information as **confidential** and ensure its personnel are bound by confidentiality (s.20);\n3. Establish and maintain the **security measures** required by s.19 — appropriate, reasonable technical and organisational measures against loss, damage, unauthorised destruction and unlawful access (s.21(1));\n4. **Notify the Responsible Party immediately** where there are reasonable grounds to believe personal information has been accessed or acquired by an unauthorised person (s.21(2));\n5. Not engage a sub-operator without prior written consent, and impose these same obligations on any approved sub-operator;\n6. Not transfer personal information outside South Africa except as authorised in writing and in compliance with s.72;\n7. Allow the Responsible Party to audit compliance with this agreement on reasonable notice;\n8. On termination, **return or securely destroy** all personal information as directed, and certify destruction.\n\n## 3. Liability and breach\n[Indemnity / limitation of liability as agreed.] A breach of this agreement is a material breach of the main services agreement.\n\nSigned for the Responsible Party: ______________________  Date: [DATE]\n\nSigned for the Operator: ______________________  Date: [DATE]'),

  ('crossborder_assessment','Cross-Border Transfer Assessment (POPIA s.72)',
E'# Cross-Border Transfer Assessment (POPIA s.72)\n\nComplete one assessment per offshore recipient before any transfer of personal information outside South Africa.\n\n| | |\n|---|---|\n| Recipient | [RECIPIENT NAME] |\n| Country / jurisdiction | [COUNTRY] |\n| PI categories transferred | [Categories] |\n| Purpose of transfer | [Purpose] |\n| Volume / frequency | [e.g. continuous hosting / monthly batch] |\n\n## Assessment\n1. **Ground relied on (s.72(1))** — [law, binding corporate rules or binding agreement providing adequate protection / consent / contract necessity / benefit of the data subject].\n2. **Adequacy of protection** — [Does the recipient jurisdiction or agreement uphold principles substantially similar to POPIA''s conditions, including restrictions on onward transfer?]\n3. **Contractual safeguards** — [Operator agreement / data-transfer clauses in place? Reference.]\n4. **Security measures at recipient** — [Encryption, access control, breach notification obligations.]\n5. **Residual risk & decision** — [Approve / approve with conditions / reject.]\n\nAssessed by: [IO NAME], Information Officer · Date: [DATE]\n\n_Record the outcome in the cross-border transfer register. Reassess annually and on material change._'),

  ('dsr_identity_sop','Data Subject Request — Identity Verification SOP',
E'# Data Subject Request — Identity Verification SOP\n\nIdentity is verified **before** any personal information is disclosed, corrected or deleted in response to a data subject request (supports POPIA s.23-25 and the DSR Procedure).\n\n## Acceptable proof of identity\n- SA ID document / smart card, or passport (certified copy or sighted original);\n- For email requests: copy of ID plus a match against the contact details on record;\n- For a requester acting on behalf of another (parent/guardian, attorney): proof of authority (e.g. mandate, court order) **and** identity of both parties;\n- For children''s PI (s.35): proof that the requester is the parent, guardian or competent person.\n\n## Steps\n1. Log the request in the DSR log before verification starts.\n2. Request the applicable proof above; do not disclose any PI in the interim.\n3. Match the proof against records held; for high-risk disclosures use a second factor (call-back on the number on record / in person).\n4. Record in the DSR log: verification method, evidence sighted, verifier, date.\n5. If verification fails or is not completed within [14] days, decline the request and inform the requester that they may resubmit with proof.\n\nNever release personal information to an unverified requester — a wrongful disclosure is itself a security compromise (s.19 / s.22).\n\n_Owner: Information Officer._'),

  ('dsr_log','Data Subject Request Log',
E'# Data Subject Request Log\n\nEvery access, correction, deletion, objection or opt-out request is logged here (POPIA s.23-25; PAIA Form 2 for access requests). Request records are retained for 3 years from the response date.\n\n| Ref | Date received | Data subject | Type (access / correction / deletion / objection / opt-out) | Identity verified (date, method) | Acknowledged (3 business days) | Response due | Outcome | Closed |\n|---|---|---|---|---|---|---|---|---|\n| [DSR-001] | [DATE] | [name] | [access] | [DATE, ID sighted] | [DATE] | [DATE] | [granted / partially granted / refused + grounds] | [DATE] |\n\n## Response timeframes\n- Acknowledgement: within 3 business days\n- PAIA access request: within 30 days (extendable to 60 days for complex requests)\n- Correction / deletion: within 15 business days\n- Objection: within 15 business days\n- Direct marketing opt-out: immediate / within 1 business day\n\n_Owner: Information Officer · Reviewed monthly for overdue requests._'),

  -- ── Phase 6 — Incident response & monitoring ───────────────────────────────

  ('breach_register','Breach Register',
E'# Breach Register\n\nAll actual and suspected security compromises are recorded here (POPIA s.22). Breach and incident records are retained for 3 years from the incident date.\n\n| Ref | Date detected | Description | PI / systems affected | Data subjects (count) | Risk of harm | Contained (date) | Regulator notified (date / ref) | Data subjects notified (date / method) | Root cause | Corrective actions | Review done | Closed |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| [BR-001] | [DATE] | [e.g. phishing-compromised mailbox] | [Mailbox / customer PI] | [count] | [High / medium / low + rationale] | [DATE] | [DATE / ref] | [DATE / email] | [cause] | [actions] | [DATE] | [DATE] |\n\n## Notification rule (s.22)\nNotify the **Information Regulator** as soon as reasonably possible after discovery of a compromise, and **affected data subjects** where there is a risk of harm — unless a public body responsible for detection or investigation requires a delay. Notifications are sent via [BREACH CONTACT / IO EMAIL].\n\n## On detection (summary — see the Data Breach Response Procedure)\nActivate the Incident Response Plan; contain and investigate; notify; record here; conduct a post-incident review.\n\n_Owner: Information Officer · Every entry cross-references the incident record and post-incident review._')

) AS x(slot_key,name,body)
ON CONFLICT (framework_key, slot_key, version) DO NOTHING;

COMMIT;
