-- Awareness interview instrument v1 for POPIA — pure content, zero schema change.
-- 41 behavioural questions across 7 domains, modelled on William's Puris engagement
-- instrument (ISO 27001:2022 Annex A / NIST CSF 2.0 / POPIA). Question wording is a
-- faithful draft pending William's source workbook — pack metadata carries the flag;
-- refining wording later is an UPDATE, never a schema change.
--
-- Ships as the next global popia content-pack version. create_assessment was hardened in
-- 20260828000004 to skip packs without assessment questions, so this cannot capture new
-- POPIA assessments.

BEGIN;

INSERT INTO public.content_packs (practice_id, framework_key, version, label, status, metadata)
SELECT NULL, 'popia',
       (SELECT COALESCE(max(version), 0) + 1 FROM public.content_packs
         WHERE framework_key = 'popia' AND practice_id IS NULL),
       'Security & Privacy Awareness Interview v1 (ISO 27001:2022 / NIST CSF 2.0 / POPIA)',
       'published',
       '{"instrument": "awareness_interview",
         "source": "Modelled on the Puris engagement instrument (2026)",
         "content_status": "draft_pending_william",
         "thresholds": {"low": 80, "high": 50}}'::jsonb;

INSERT INTO public.awareness_questions
  (content_pack_id, framework_key, domain_code, domain_name, code, question_number,
   question, good_answer, guidance, regulatory_ref)
SELECT cp.id, 'popia', v.dc, v.dn, v.code, v.qn, v.q, v.good, v.g, v.ref
FROM public.content_packs cp,
(VALUES
  -- Policy, training & awareness (5)
  ('POL','Policy, training & awareness','POL-01',1,
   $q$Do you know who your organisation's Information Officer is?$q$,'yes',
   $q$Every employee should know who is accountable for POPIA and where to take privacy questions.$q$,
   $q$POPIA s.55-56 | ISO 27001:2022 A.5.2$q$),
  ('POL','Policy, training & awareness','POL-02',2,
   $q$Have you read your organisation's privacy / POPIA policy?$q$,'yes',
   $q$Policies only operate when staff have actually read them.$q$,
   $q$POPIA s.55 | ISO 27001:2022 A.5.1$q$),
  ('POL','Policy, training & awareness','POL-03',3,
   $q$Have you received information security or privacy training in the last 12 months?$q$,'yes',
   $q$Annual refresher training is the baseline for the reasonable-measures test.$q$,
   $q$POPIA s.19 | ISO 27001:2022 A.6.3 | NIST CSF 2.0 PR.AT$q$),
  ('POL','Policy, training & awareness','POL-04',4,
   $q$Do you know where to find your organisation's security and privacy policies?$q$,'yes',
   $q$Staff should be able to locate the current policy set without asking.$q$,
   $q$ISO 27001:2022 A.5.1$q$),
  ('POL','Policy, training & awareness','POL-05',5,
   $q$Could you explain what counts as personal information under POPIA?$q$,'yes',
   $q$Recognising personal information is the precondition for protecting it.$q$,
   $q$POPIA s.1 | ISO 27701 7.2.1$q$),
  -- Access & authentication (8)
  ('ACC','Access & authentication','ACC-01',6,
   $q$Do you use your own account for work systems, rather than a shared team login?$q$,'yes',
   $q$Shared accounts break accountability and audit trails.$q$,
   $q$ISO 27001:2022 A.5.16 | NIST CSF 2.0 PR.AA-01$q$),
  ('ACC','Access & authentication','ACC-02',7,
   $q$Do you use an approved password manager for your work passwords?$q$,'yes',
   $q$A password manager is the only realistic route to strong, unique passwords.$q$,
   $q$ISO 27001:2022 A.5.17$q$),
  ('ACC','Access & authentication','ACC-03',8,
   $q$Is multi-factor authentication enabled on your work accounts?$q$,'yes',
   $q$MFA is the single most effective control against account takeover.$q$,
   $q$ISO 27001:2022 A.5.17 | NIST CSF 2.0 PR.AA-03$q$),
  ('ACC','Access & authentication','ACC-04',9,
   $q$Do you ever share your passwords or MFA codes with anyone - colleagues, IT staff or a manager?$q$,'no',
   $q$Credentials are personal. IT never needs your password; sharing breaks accountability.$q$,
   $q$ISO 27001:2022 A.5.16-5.17 | POPIA s.19$q$),
  ('ACC','Access & authentication','ACC-05',10,
   $q$Do you reuse your work password on other websites or services?$q$,'no',
   $q$A breach of any other site then exposes the work account.$q$,
   $q$ISO 27001:2022 A.5.17$q$),
  ('ACC','Access & authentication','ACC-06',11,
   $q$Do you lock your screen whenever you leave your desk?$q$,'yes',
   $q$An unlocked screen is unrestricted access to everything you can see.$q$,
   $q$ISO 27001:2022 A.7.7 | A.8.1$q$),
  ('ACC','Access & authentication','ACC-07',12,
   $q$Are your work passwords long passphrases (12 characters or more)?$q$,'yes',
   $q$Length beats complexity; short passwords fall to automated guessing.$q$,
   $q$ISO 27001:2022 A.5.17$q$),
  ('ACC','Access & authentication','ACC-08',13,
   $q$Do you write passwords down anywhere others could find them?$q$,'no',
   $q$A note under the keyboard defeats every technical control.$q$,
   $q$ISO 27001:2022 A.5.17$q$),
  -- Email & social engineering (6)
  ('EML','Email & social engineering','EML-01',14,
   $q$Do you check the sender's actual email address before acting on a message?$q$,'yes',
   $q$Display names are trivially forged; the address is the first tell.$q$,
   $q$ISO 27001:2022 A.6.3 | NIST CSF 2.0 PR.AT$q$),
  ('EML','Email & social engineering','EML-02',15,
   $q$Would you verify a request to change bank details or make an urgent payment by phoning the requester on a known number?$q$,'yes',
   $q$Business email compromise is the most expensive attack on SMEs; out-of-band verification defeats it.$q$,
   $q$ISO 27001:2022 A.5.14 | NIST CSF 2.0 PR.AT$q$),
  ('EML','Email & social engineering','EML-03',16,
   $q$Do you know how to report a suspicious email?$q$,'yes',
   $q$Reporting one phish protects everyone who received it.$q$,
   $q$ISO 27001:2022 A.6.8$q$),
  ('EML','Email & social engineering','EML-04',17,
   $q$Have you clicked a link or opened an attachment in an unexpected email without checking it first?$q$,'no',
   $q$One click is all ransomware needs.$q$,
   $q$ISO 27001:2022 A.8.7$q$),
  ('EML','Email & social engineering','EML-05',18,
   $q$When a message creates urgency or pressure, do you slow down and verify before responding?$q$,'yes',
   $q$Manufactured urgency is the core social-engineering technique.$q$,
   $q$NIST CSF 2.0 PR.AT$q$),
  ('EML','Email & social engineering','EML-06',19,
   $q$Do you open attachments from senders you don't recognise?$q$,'no',
   $q$Unknown attachments are the classic malware delivery route.$q$,
   $q$ISO 27001:2022 A.8.7$q$),
  -- Devices, remote work & network (6)
  ('DEV','Devices, remote work & network','DEV-01',20,
   $q$Is the device you work on encrypted and protected by a password or biometric?$q$,'yes',
   $q$Encryption is what turns a lost laptop from a breach into an inconvenience.$q$,
   $q$ISO 27001:2022 A.8.1 | POPIA s.19$q$),
  ('DEV','Devices, remote work & network','DEV-02',21,
   $q$Do you install system and application updates promptly when prompted?$q$,'yes',
   $q$Most compromises exploit patches that already existed.$q$,
   $q$ISO 27001:2022 A.8.8 | NIST CSF 2.0 ID.RA$q$),
  ('DEV','Devices, remote work & network','DEV-03',22,
   $q$Do you use a personal device for work without it being approved and set up by IT?$q$,'no',
   $q$Unmanaged devices sit outside every control the organisation operates.$q$,
   $q$ISO 27001:2022 A.6.7 | A.8.1$q$),
  ('DEV','Devices, remote work & network','DEV-04',23,
   $q$Do you use public or open Wi-Fi for work without a VPN?$q$,'no',
   $q$Open networks expose credentials and data in transit; use a VPN or hotspot.$q$,
   $q$ISO 27001:2022 A.8.20-8.21 | NIST CSF 2.0 PR.DS$q$),
  ('DEV','Devices, remote work & network','DEV-05',24,
   $q$Do you use USB drives or other removable media to move work data?$q$,'no',
   $q$Removable media bypasses backups, retention and access control - and gets lost.$q$,
   $q$ISO 27001:2022 A.7.10 | POPIA s.14, s.19$q$),
  ('DEV','Devices, remote work & network','DEV-06',25,
   $q$If your work device were lost or stolen, would you report it the same day?$q$,'yes',
   $q$The first hours decide whether a lost device becomes a notifiable breach.$q$,
   $q$ISO 27001:2022 A.6.8 | POPIA s.22$q$),
  -- Data handling & privacy (8)
  ('DAT','Data handling & privacy','DAT-01',26,
   $q$Do you know which of the information you handle day-to-day is personal information?$q$,'yes',
   $q$You cannot apply handling rules to data you have not recognised as personal.$q$,
   $q$POPIA s.1 | ISO 27701 7.2.1$q$),
  ('DAT','Data handling & privacy','DAT-02',27,
   $q$Do you only access personal information you actually need for your job?$q$,'yes',
   $q$Curiosity browsing of customer or staff records is unlawful processing.$q$,
   $q$POPIA s.10-11 | ISO 27001:2022 A.5.15$q$),
  ('DAT','Data handling & privacy','DAT-03',28,
   $q$Do you double-check the recipients before emailing personal information?$q$,'yes',
   $q$Misdirected email is the most common reported breach type.$q$,
   $q$POPIA s.19 | ISO 27001:2022 A.5.14$q$),
  ('DAT','Data handling & privacy','DAT-04',29,
   $q$Do you use personal email, WhatsApp or personal cloud storage for work information?$q$,'no',
   $q$Work data on personal accounts is unprotected, unretained, unsearchable for access requests and unrecoverable at offboarding.$q$,
   $q$POPIA s.14, s.19 | ISO 27001:2022 A.5.14$q$),
  ('DAT','Data handling & privacy','DAT-05',30,
   $q$Do you shred or securely dispose of paper documents containing personal information?$q$,'yes',
   $q$The bin is a public disclosure channel.$q$,
   $q$POPIA s.14(1) | ISO 27001:2022 A.7.14$q$),
  ('DAT','Data handling & privacy','DAT-06',31,
   $q$Do you leave documents containing personal information on your desk or at the printer?$q$,'no',
   $q$Clear desk and clear printer are the paper equivalent of a locked screen.$q$,
   $q$ISO 27001:2022 A.7.7$q$),
  ('DAT','Data handling & privacy','DAT-07',32,
   $q$Would you check with the Information Officer before sharing personal information with a third party?$q$,'yes',
   $q$Third-party disclosure needs a lawful basis and often a contract.$q$,
   $q$POPIA s.20-21, s.72$q$),
  ('DAT','Data handling & privacy','DAT-08',33,
   $q$Do you know what to do if a person asks for access to the personal information you hold about them?$q$,'yes',
   $q$Data subject requests carry statutory deadlines; recognising one is step zero.$q$,
   $q$POPIA s.23-25 | PAIA$q$),
  -- Incident reporting (4)
  ('INC','Incident reporting','INC-01',34,
   $q$Do you know how to report a security or privacy incident in your organisation?$q$,'yes',
   $q$A procedure nobody knows about does not operate.$q$,
   $q$POPIA s.22 | ISO 27001:2022 A.6.8$q$),
  ('INC','Incident reporting','INC-02',35,
   $q$If you accidentally sent personal information to the wrong person, would you report it immediately?$q$,'yes',
   $q$The regulator judges the response as much as the mistake.$q$,
   $q$POPIA s.22$q$),
  ('INC','Incident reporting','INC-03',36,
   $q$Would you recognise the signs that personal information has been breached or compromised?$q$,'yes',
   $q$Detection by staff is usually the first line of breach discovery.$q$,
   $q$POPIA s.22 | NIST CSF 2.0 DE.CM$q$),
  ('INC','Incident reporting','INC-04',37,
   $q$Would you report an incident even if the mistake was your own?$q$,'yes',
   $q$A blame culture hides breaches until they are unmanageable.$q$,
   $q$ISO 27001:2022 A.6.8$q$),
  -- AI tools & shadow IT (4)
  ('AIT','AI tools & shadow IT','AIT-01',38,
   $q$Do you paste company or personal information into public AI tools such as ChatGPT?$q$,'no',
   $q$Public AI services may retain and train on whatever is pasted in.$q$,
   $q$POPIA s.19, s.72 | ISO 27001:2022 A.5.14$q$),
  ('AIT','AI tools & shadow IT','AIT-02',39,
   $q$Do you use software or cloud services for work that IT has not approved?$q$,'no',
   $q$Shadow IT sits outside backup, retention, access control and contracts.$q$,
   $q$ISO 27001:2022 A.5.19 | POPIA s.20-21$q$),
  ('AIT','AI tools & shadow IT','AIT-03',40,
   $q$Do you know whether your organisation has rules on using AI tools at work?$q$,'yes',
   $q$Knowing the rule exists is the difference between policy and folklore.$q$,
   $q$ISO 27001:2022 A.5.1$q$),
  ('AIT','AI tools & shadow IT','AIT-04',41,
   $q$Would you check before putting work data into a new online tool for the first time?$q$,'yes',
   $q$Every new tool is a new processor relationship with POPIA obligations.$q$,
   $q$POPIA s.20-21$q$)
) AS v(dc, dn, code, qn, q, good, g, ref)
WHERE cp.framework_key = 'popia' AND cp.practice_id IS NULL
  AND cp.label = 'Security & Privacy Awareness Interview v1 (ISO 27001:2022 / NIST CSF 2.0 / POPIA)';

COMMIT;

NOTIFY pgrst, 'reload schema';
